# core/downloader.py

import json
import os
import re
import shutil
import threading
import time
import yt_dlp
import yt_dlp.utils

from typing import Optional, Callable, List, Tuple, Any

from core.ydl_logger import YDLLogger
from core.audio import Audio
from utils.helpers import safe_float
from utils.paths import get_ffmpeg_path
from utils.audio_tags import is_normalized, mark_as_normalized
from utils.sanitize import sanitize_filename
from i18n.manager import I18nManager
from utils.app_config import get_state_file


# Regex to detect intermediate files generated by yt-dlp
YTDLP_INTERMEDIATE_RE = re.compile(r"\.f\d+\.(webm|mp4|mkv|m4a|aac|opus)(\.part)?$", re.IGNORECASE)

# Supported final audio/video extensions
MAIN_EXTS = {".mp3", ".wav", ".flac", ".m4a", ".aac", ".opus", ".mp4", ".mkv", ".webm"}

# Browsers used as fallback for cookies authentication
BROWSER_FALLBACK: list = ["chrome", "edge", "firefox", "opera"]

# Error markers indicating authentication or restriction issues
AUTH_ERROR_MARKERS = (
    "this video is private",
    "sign in",
    "age-restricted",
    "sign in to confirm your age",
    "members-only",
    "members-only content",
    "login required",
    "private video",
    "this video is unavailable"
)


def _safe_dict(value) -> dict:
    """
    Ensure the returned value is always a dictionary.

    :param value: Any value that may or may not be a dictionary.
    :type value: Any
    :return: A dictionary instance (empty if input is not a dict).
    :rtype: dict
    """

    return value if isinstance(value, dict) else {}


class Downloader:
    """
    Handles YouTube audio/video downloads using yt-dlp.

    Features:
        - Single video and playlist downloads
        - Manual playlist selection
        - Audio normalization (LUFS)
        - Pause, resume and cancel
        - Authentication retry using browser cookies
        - Temporary file cleanup
        - UI integration via hooks

    Optional hooks:
        - progress_hook(percent, playlist_index, playlist_count, status_text)
        - status_hook(message)
        - file_finished_hook(file_path)
        - error_hook(error_message)
        - log_hook(log_message)
        - confirm_keep_hook(file_path) -> bool
    """

    def __init__(
        self,
        url: str,
        output_path: str,
        audio_format: str = "mp3",
        quality: str = "192",
        resolution: str = "Auto",
        allow_playlist: bool = False,
        keep_original_file: bool = False,
        normalize_enabled: bool = False,
        progress_hook: Optional[Callable[..., None]] = None,
        status_hook: Optional[Callable[[str], None]] = None,
        file_finished_hook: Optional[Callable[[str], None]] = None,
        error_hook: Optional[Callable[[str], None]] = None,
        log_hook: Optional[Callable[[str], None]] = None,
        confirm_keep_hook: Optional[Callable[[str], bool]] = None,
        state_file: Optional[str] = None,
        language: Optional[str] = "en-US",
    ) -> None:
        """
        Initialize the downloader instance.

        :param url: Video or playlist URL.
        :type url: str
        :param output_path: Base output directory.
        :type output_path: str
        :param audio_format: Desired audio format (e.g. mp3, wav).
        :type audio_format: str
        :param quality: Audio quality or bitrate.
        :type quality: str
        :param resolution: Target video resolution.
        :type resolution: str
        :param allow_playlist: Whether playlists are allowed.
        :type allow_playlist: bool
        :param keep_original_file: Keep original video file after extraction.
        :type keep_original_file: bool
        :param normalize_enabled: Enable LUFS audio normalization.
        :type normalize_enabled: bool
        :param progress_hook: Callback for progress updates.
        :type progress_hook: Optional[Callable[..., None]]
        :param status_hook: Callback for status messages.
        :type status_hook: Optional[Callable[[str], None]]
        :param file_finished_hook: Callback when a file finishes processing.
        :type file_finished_hook: Optional[Callable[[str], None]]
        :param error_hook: Callback for error notifications.
        :type error_hook: Optional[Callable[[str], None]]
        :param log_hook: Callback for log output.
        :type log_hook: Optional[Callable[[str], None]]
        :param confirm_keep_hook: Callback to confirm keeping file on cancel.
        :type confirm_keep_hook: Optional[Callable[[str], bool]]
        :param state_file: Optional custom path for state file.
        :type state_file: Optional[str]
        :param language: Language code for i18n messages.
        :type language: Optional[str]
        """

        # ===============================
        # Core configuration
        # ===============================
        self.language: str = language
        self.i18n: I18nManager = I18nManager(language=self.language)

        self.pending_pause: Optional[bool] = None
        self.source_url: str = url
        self.url: str = url
        self.output_path: str = output_path
        self.audio_format: str = audio_format
        self.quality: str = quality
        self.resolution: str = resolution
        self.allow_playlist: bool = allow_playlist
        self.keep_original_file: bool = keep_original_file
        self.normalize_enabled: bool = normalize_enabled

        # ===============================
        # Hooks for UI/controller callbacks
        # ===============================
        self.progress_hook: Optional[Callable[..., None]] = progress_hook
        self.status_hook: Optional[Callable[[str], None]] = status_hook
        self.file_finished_hook: Optional[Callable[[str], None]] = file_finished_hook
        self.error_hook: Optional[Callable[[str], None]] = error_hook
        self.log_hook: Optional[Callable[[str], None]] = log_hook
        self.confirm_keep_hook: Optional[Callable[[str], bool]] = confirm_keep_hook

        # ===============================
        # Internal state
        # ===============================
        self.ffmpeg_path: str = get_ffmpeg_path()
        self.generated_files: set[str] = set()
        self.canceled_files: set[str] = set()
        self.files_to_normalize: List[Tuple[str, str]] = []
        self.collected_files: list[str] = []

        self.tmp_dir: Optional[str] = None
        self.tmp_playlist_dir: Optional[str] = None
        self.playlist_dir: Optional[str] = None

        self.playlist_index: Optional[int] = None
        self.playlist_count: Optional[int] = None

        self._cached_info: Optional[dict] = None
        self._cached_flat: bool = False
        self._extract_cache: dict[str, dict] = {}

        self.cancel_requested: bool = False
        self.cancel_after_current: bool = False
        self.keep_after_cancel: bool = False

        self.cookies_from_browser: Optional[str] = None
        self.browser_retry_index: int = 0

        self.paused: bool = False
        self.pause_event: threading.Event = threading.Event()
        self.pause_event.set()  # Not paused by default

        self.selected_entries: Optional[List[dict]] = None
        self.blocked_files: set[str] = set()
        self.canceled_titles: set[str] = set()

        self._download_active: bool = False
        self.STATE_FILE: str = get_state_file() or state_file

        self.ydl_opts: dict[str, Any] = {}

        self.current_info: Optional[dict] = None
        self.failed_video_id: Optional[str] = None

        # ===============================
        # Authentication retry state
        # ===============================
        self._auth_retry_index: int = 0
        self._retrying_auth: bool = False

        self._auth_retry_browsers: list[str] = [
            "edge",
            "chrome",
            "firefox",
            "opera"
        ]

        self._extra_ydl_opts: dict[str, Any] = {}
        self._restricted_alert_shown: bool = False

        # ===============================
        # Manual playlist selection
        # ===============================
        self.playlist_title: Optional[str] = None
        self.selected_entries = None
        self.is_manual_selection: bool = False

        self._alerted_private: bool = False
        self._logged_resolution: bool = False

        # ===============================
        # Internal thread safety lock
        # ===============================
        self._lock: threading.Lock = threading.Lock()

    # ===============================
    # Public methods
    # ===============================
    def start(self) -> None:
        """
        Start the download process.

        This method initializes the internal state, cleans orphan temporary files
        from previous crashes, prepares directories, extracts metadata, and
        triggers either playlist or single video download flow.
        """

        self._download_active: bool = True
        self._logged_resolution: bool = False

        # Clean orphan temporary files left by previous unexpected crashes
        self._cleanup_orphan_tmps()

        try:
            # =============================
            # RESET STATE
            # =============================
            self.tmp_playlist_dir = None
            self.playlist_dir = None
            self.playlist_index = None
            self.playlist_count = None

            self._prepare_dirs()

            # =============================
            # BUILD BASE OPTS (NO AUTH)
            # =============================
            self._build_ydl_opts()
            self.ydl_opts.pop("cookiesfrombrowser", None)

            # =============================
            # EXTRACT INFO (LIGHT, NO AUTH)
            # =============================
            if self.selected_entries:
                self._log(
                    f"{self.i18n.t('downloader.log_selected_entries')} ({len(self.selected_entries)} item(s))",
                    self.i18n.t("flow")
                )

                info = {
                    "_type": "playlist",
                    "title": self.playlist_title or "Playlist",
                    "entries": self.selected_entries,
                }

            else:
                if not self.url:
                    raise RuntimeError("No URL provided")

                info = self._extract_light_info(self.url)

                if not info:
                    raise RuntimeError("[Restrict Video]: Failed to extract video metadata")

                # Cache metadata only if the extracted content is a playlist
                if info.get("_type") == "playlist" or "entries" in info:
                    self._cached_info = info
                    self._cached_flat = True

            if not info:
                raise RuntimeError("Failed to extract info")

            is_playlist = info.get("_type") == "playlist" or "entries" in info

            # =============================
            # PLAYLIST
            # =============================
            if self.allow_playlist and is_playlist:
                self._download_playlist(info)
                return

            # =============================
            # SINGLE (FORCED)
            # =============================
            self.allow_playlist = False

            # Ensure full metadata is available for single video
            info = self.get_info(flat=False)

            if not info or not isinstance(info, dict):
                self.notify_restricted(self.i18n.t("downloader.restricted"))

                return

            self._download_single(info)

        except Exception as e:
            msg: str = str(e)

            self._error(msg)

            self._log(
                f"{self.i18n.t('downloader.log_error_download_failed')} {msg}",
                self.i18n.t("error_level")
            )

        finally:
            if not self.paused:
                self._finalize_download()

    # ===============================
    # Internal methods (download flow)
    # ===============================
    def _prepare_dirs(self) -> None:
        """
        Prepare and create required output directories.

        This method ensures the output directory exists, resets internal
        file tracking collections, and updates UI status/logs.
        """

        os.makedirs(self.output_path, exist_ok=True)

        self.generated_files.clear()
        self.canceled_files.clear()
        self.collected_files.clear()
        self.files_to_normalize.clear()

        self._set_status(self.i18n.t("downloader.status_prepare_dirs"))

        self._log(self.i18n.t("downloader.log_prepare_dirs"), self.i18n.t("start"))

    def _build_ydl_opts(self) -> None:
        """
        Build yt-dlp options dictionary.

        This method configures output paths, format selection, normalization,
        playlist behavior, post-processors, authentication handling, and
        progress hooks according to the current downloader state.
        """

        base_output = self.output_path

        # Normalization has absolute priority and forces a temporary directory
        if self.normalize_enabled:
            self.tmp_dir = os.path.join(base_output, "temp_normalize")
            os.makedirs(self.tmp_dir, exist_ok=True)
            output_dir = self.tmp_dir

        # Playlist temporary directory when normalization is disabled
        elif self.allow_playlist and self.tmp_playlist_dir:
            output_dir = self.tmp_playlist_dir

        # Default output directory
        else:
            output_dir = base_output

        self.ydl_opts = {
            "format": self._build_format_string(),
            "ffmpeg_location": self.ffmpeg_path,

            "outtmpl": os.path.join(
                output_dir,
                "%(title)s [%(id)s].%(ext)s"
            ),

            "noplaylist": not self.allow_playlist,
            "merge_output_format": "mp4",
            "external_downloader_args": ["-nostdin"],
            "keepvideo": self.keep_original_file,

            "progress_hooks": [self._progress_hook],
            "postprocessor_hooks": [self._postprocessor_hook],

            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": self.audio_format,
                    "preferredquality": self.quality,
                }
            ],

            "restrictfilenames": True,
            "nopart": False,
            "quiet": True,
            "no_warming": True,
            "logger": YDLLogger(self),
            "ignoreerrors": True,
            "continuedl": True
        }

        self.ydl_opts.update(self._extra_ydl_opts)

        # Authentication extractor configuration
        if self._retrying_auth or self.cookies_from_browser:
            self.ydl_opts["extractor_args"] = {
                "youtube": {
                    "player_client": ["web", "tv_embedded"]
                }
            }
        else:
            self.ydl_opts.pop("extractor_args", None)

    # ===============================
    # Internal download methods
    # ===============================
    def _download_playlist(self, info: dict) -> None:
        """
        Download playlist entries.

        This method handles playlist directory creation, manual entry selection,
        cache validation, authentication retry, and sequential video downloads
        without re-expanding playlist metadata.

        :param info: Playlist metadata dictionary
        :type info: dict
        """

        playlist_name = sanitize_filename(
            self.playlist_title
            or info.get("title")
            or "Playlist"
        )

        self.playlist_dir = os.path.join(self.output_path, playlist_name)
        os.makedirs(self.playlist_dir, exist_ok=True)

        self.tmp_playlist_dir = os.path.join(
            self.output_path,
            f".tmp_playlist_{playlist_name}_{int(time.time())}"
        )
        os.makedirs(self.tmp_playlist_dir, exist_ok=True)

        # -------------------------------
        # Build base options
        # -------------------------------
        self._build_ydl_opts()

        if not self.normalize_enabled:
            self.ydl_opts["outtmpl"] = os.path.join(
                self.tmp_playlist_dir,
                "%(title)s [%(id)s].%(ext)s"
            )

        # -------------------------------
        # Resolve manual selection
        # -------------------------------
        selected_ids = None
        if self.selected_entries:
            selected_ids = {
                e.get("id") for e in self.selected_entries if e and e.get("id")
            }

        entries_to_download: list = []

        # -------------------------------
        # FILTER PHASE (no download here)
        # -------------------------------
        for entry in info.get("entries", []):
            if not entry:
                continue

            video_id = entry.get("id")
            if not video_id:
                continue

            if selected_ids and video_id not in selected_ids:
                continue

            title = sanitize_filename(entry.get("title", "untitled"))
            final_base = os.path.join(
                self.playlist_dir,
                f"{title} [{video_id}]"
            )

            if self._should_download(final_base):
                entries_to_download.append(entry)
            else:
                self._log(f"{self.i18n.t('downloader.log_skipping_cached')} {title}", self.i18n.t("cache"))

        if not entries_to_download:
            self._log(self.i18n.t("downloader.log_error_not_entries"), self.i18n.t("cache"))

            shutil.rmtree(self.tmp_playlist_dir, ignore_errors=True)

            return

        # -------------------------------
        # DOWNLOAD PHASE (NO RE-EXTRACT)
        # -------------------------------
        self._apply_cookies_if_needed()

        for entry in entries_to_download:
            self._reset_auth_retry()
            self.current_info = entry
            self.failed_video_id = entry.get("id")

            while True:
                try:
                    self._build_ydl_opts()
                    self._apply_cookies_if_needed()

                    with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
                        # 🔥 ONE VIDEO ONLY — no playlist expansion
                        ydl.process_ie_result(entry, download=True)

                    break  # ✅ success

                except Exception as e:
                    msg = str(e)

                    if self._is_auth_error(msg):
                        if self._try_next_browser_cookie():
                            continue

                        title = entry.get("title", self.i18n.t("downloader.unknown_video_title"))

                        self._log(
                            f"{self.i18n.t('downloader.log_error_restricted_private')} {title}",
                            self.i18n.t("skip")
                        )

                        # 🔔 notify UI ONCE
                        self._set_status(f"{self.i18n.t('downloader.status_skipped_restricted')} {title}")

                        if not self._restricted_alert_shown:
                            self._restricted_alert_shown: bool = True
                            self._error(self.i18n.t("downloader.error_download_playlist"))

                        break

                    raise

    def _download_single(self, info: dict) -> None:
        """
        Download a single video.

        This method handles downloading a single video outside of playlist mode.
        It supports authentication retry logic, cache checking, and immediate
        download execution using yt-dlp.

        :param info: Video metadata dictionary
        :type info: dict
        """

        self._build_ydl_opts()

        video_id = info.get("id")
        title = sanitize_filename(info.get("title", self.i18n.t("downloader.unknown_video_title")))

        if video_id:
            base_path = os.path.join(
                self.output_path,
                f"{title} [{video_id}]"
            )

            # Skip download if file already exists or cache rules apply
            if not self._should_download(base_path):
                self._log({self.i18n.t("downloader.log_not_should_download")}, self.i18n.t("cache"))

                return

        # -------------------------------
        # Prepare authentication retry state
        # -------------------------------
        self._reset_auth_retry()
        self.current_info = info
        self.failed_video_id = info.get("id")

        while True:
            try:
                self._build_ydl_opts()
                self._apply_cookies_if_needed()

                with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
                    ydl.process_ie_result(info, download=True)

                break  # ✅ Download succeeded

            except Exception as e:
                msg: str = str(e)

                # Handle authentication-related errors
                if self._is_auth_error(msg):
                    if self._try_next_browser_cookie():
                        continue

                    self._log(
                        f"{self.i18n.t('downloader.log_error_auth_failed')} {info.get('id')}",
                        self.i18n.t("skip")
                    )

                    return

                raise

    def _finalize_download(self) -> None:
        """
        Finalize the download process.

        This method is executed after yt-dlp finishes its execution.
        It handles normalization, file movement, cleanup of temporary directories,
        and proper shutdown logic depending on cancel and pause states.
        """

        # =============================
        # CANCELLED + KEEP
        # =============================
        if self.cancel_requested and self.keep_after_cancel:
            self._log(self.i18n.t("downloader.log_cancel_keep"), self.i18n.t("cancel_level"))

            self.normalize_move_and_clean()

            # Move normalized files back to output directory for single downloads
            if (
                    self.normalize_enabled
                    and not self.allow_playlist
                    and self.tmp_dir
                    and os.path.exists(self.tmp_dir)
            ):
                for f in os.listdir(self.tmp_dir):
                    src = os.path.join(self.tmp_dir, f)
                    dst = os.path.join(self.output_path, f)

                    if os.path.exists(dst):
                        continue

                    shutil.move(src, dst)

                shutil.rmtree(self.tmp_dir, ignore_errors=True)

            self._cleanup_after_cancel_or_finished()

            return

        # =============================
        # CANCELLED WITHOUT KEEPING FILES
        # =============================
        if self.cancel_requested and not self.keep_after_cancel:
            self._log(self.i18n.t("downloader.log_cancel_no_keep"), self.i18n.t("cancel_level"))

            # Remove only playlist temporary directory
            if self.tmp_playlist_dir:
                shutil.rmtree(self.tmp_playlist_dir, ignore_errors=True)

            self._cleanup_after_cancel_or_finished()

            return

        # =============================
        # NORMAL COMPLETION FLOW
        # =============================
        if not self.paused:
            self.normalize_move_and_clean()

            self._cleanup_after_cancel_or_finished()

    # ===============================
    # Cancel method
    # ===============================
    def cancel(self, after_current: bool = False) -> None:
        """
        Cancel the download process.

        :param after_current: If True, cancel only after the current playlist item finishes.
        :type after_current: bool
        """

        # Pause execution immediately
        self.pause_event.set()

        # Deferred cancel for playlist mode
        if after_current and self.allow_playlist:
            self.cancel_after_current: bool = True

            self._log(self.i18n.t("downloader.log_cancel_after_current"), self.i18n.t("cancel_level"))

        # Immediate cancel
        else:
            self.cancel_requested = True
            self.cancel_after_current: bool = False

            self._log(self.i18n.t("downloader.log_cancel_immediate"), self.i18n.t("cancel_level"))

    # ==============================
    # Hooks for yt-dlp
    # ==============================
    def _progress_hook(self, d: dict) -> None:
        """
        yt-dlp progress hook.

        Reports download progress, manages pause and cancel requests,
        tracks generated temporary and final files, and updates UI callbacks.

        :param d: yt-dlp progress dictionary
        :type d: dict
        """

        # Apply deferred pause on first progress callback
        if self.pending_pause:
            self.pause_event.clear()
            self.pending_pause = False

        # Block execution while paused
        self.pause_event.wait()

        # Capture generated temporary and final file paths
        for key in ("tmpfilename", "filename"):
            path: str = d.get(key)

            if path:
                self.generated_files.add(os.path.abspath(path))

        # ===============================
        # 1️⃣ Main file progress only
        # ===============================
        filename: str = d.get("filename") or d.get("tmpfilename")

        ext: str = os.path.splitext(filename or "")[1].lower()
        is_main_file: bool = ext in MAIN_EXTS

        if is_main_file and filename and hasattr(self, "audio_format") and self.audio_format:
            # Build display filename for logs (does not modify files)
            display_filename: str = os.path.basename(filename)
            display_filename: str = re.sub(r'\.f\d+\.', '.', display_filename)  # remove intermediary
            display_filename: str = os.path.splitext(display_filename)[0]  # remove original extension
            display_filename: str = f"{display_filename}.{self.audio_format.lower()}"

            status: str | None = d.get("status")
            playlist_index: str | None = d.get("playlist_index")
            playlist_count: str | None = d.get("playlist_count")

            if status == "downloading":
                info: dict = d.get("info_dict") or {}

                if self.keep_original_file:
                    fmt = info.get("format")
                    height = info.get("height")
                    fps = info.get("fps")
                    vcodec = info.get("vcodec")

                    self._log(
                        f"{self.i18n.t('downloader.log_format_resolution')} {fmt} — {height}p @ {fps}fps — {vcodec}",
                        self.i18n.t("info")
                    )
                    self._logged_resolution = True

                downloaded_bytes: float = safe_float(d.get("downloaded_bytes"))
                total_bytes: float = safe_float(d.get("total_bytes") or d.get("total_bytes_estimate"), 1)
                percent: float = (downloaded_bytes / total_bytes * 100) if total_bytes else 0.0
                speed: float = safe_float(d.get("speed"))
                eta: int = int(d.get("eta") or 0)

                downloaded_mb: float = downloaded_bytes / (1024 * 1024)
                total_mb: float = total_bytes / (1024 * 1024)

                status_text: str = f"{percent:5.1f}% — {downloaded_mb:.2f}/{total_mb:.2f} MB — " \
                                   f"{speed / 1024:.2f} KB/s — ETA {eta}s"

                if playlist_index and playlist_count:
                    idx = int(playlist_index)
                    total = int(playlist_count)
                    status_text = f"{idx:02d}/{total:02d} — {status_text}"

                if downloaded_bytes == 0:
                    self._log(f"{self.i18n.t('downloader.log_starting')} {display_filename}", self.i18n.t("download_level"))

                self._log(f"{status_text}", self.i18n.t("download_level"))

                if self.progress_hook:
                    self.progress_hook(percent, playlist_index, playlist_count, status_text)

            elif status == "finished":
                abs_path: str = os.path.abspath(filename)
                self.generated_files.add(abs_path)


                self._log(f"{display_filename}", self.i18n.t("done"))

                if self.progress_hook:
                    self.progress_hook(
                        100.0,
                        d.get("playlist_index"),
                        d.get("playlist_count"),
                        f"[{self.i18n.t('done')}] {display_filename}"
                    )
        # ===============================
        # 2️⃣ Immediate Cancellation
        # ===============================
        if self.cancel_requested and not self.cancel_after_current:
            tmp_file: str = d.get("tmpfilename")

            if tmp_file and os.path.exists(tmp_file):
                try:
                    os.remove(tmp_file)
                    self._log(f"{self.i18n.t('downloader.log_remove_tmp')} {tmp_file}", self.i18n.t("cancel_level"))

                except Exception as e:
                    self._log(f"{self.i18n.t('downloader.log_error_remove_tmp')} {tmp_file} — {e}", self.i18n.t("error_level"))

            raise yt_dlp.utils.DownloadError("Download canceled by user")

    def _postprocessor_hook(self, d: dict) -> None:
        """
        yt-dlp postprocessor hook.

        Tracks generated files, resets authentication retry state,
        and handles deferred cancellation after the current item finishes.

        :param d: yt-dlp postprocessor dictionary
        :type d: dict
        """

        if d.get("status") != "finished":
            return

        info: dict = d.get("info_dict") or {}

        # Reset authentication retry state
        self._auth_retry_index = 0
        self._retrying_auth = False
        self.cookies_from_browser = None

        possible_paths: list[str] = []

        # Collect possible output paths
        for key in ("filepath", "filename", "_filename"):
            val = d.get(key) or info.get(key)
            if isinstance(val, str):
                possible_paths.append(val)

        requested = d.get("requested_downloads")
        if isinstance(requested, list):
            for item in requested:
                path = item.get("filepath") or item.get("filename")
                if path:
                    possible_paths.append(path)

        # Register generated files
        for path in possible_paths:
            abs_path = os.path.abspath(path)
            if os.path.exists(abs_path):
                self.generated_files.add(abs_path)

        # ==============================
        # Cancel after current item
        # ==============================
        if self.cancel_after_current:
            self.cancel_after_current = False

            keep = True
            main_file = possible_paths[-1] if possible_paths else None

            if main_file and os.path.exists(main_file):
                if self.confirm_keep_hook:
                    keep = self.confirm_keep_hook(main_file)

                if not keep:
                    self.canceled_files.add(os.path.abspath(main_file))

            self.keep_after_cancel = keep
            self.cancel_requested = True

            self._log(
                f"{self.i18n.t('downloader.log_cancel_wanna_keep')} {keep}",
                self.i18n.t("cancel_level")
            )

        # Reset authentication retry state on successful download
        video_id = info.get("id")

        if self.current_info and video_id == self.current_info.get("id"):
            self._auth_retry_index = 0
            self._retrying_auth = False
            self._extra_ydl_opts.clear()
            self.cookies_from_browser = None

    # ===============================
    # Normalization
    # ===============================
    def _normalize_files(self) -> None:
        """
        Normalize collected audio files to target LUFS (-14 dB).

        This method processes audio files in the temporary directory,
        moves normalized files to their final destination, and handles
        cancel and keep scenarios.
        """

        files_to_process: list = self._collect_files_for_normalize()
        tmp_dir: str = self.tmp_dir

        # Canceled + keep files: move without normalization
        if self.cancel_requested and self.keep_after_cancel:
            self._log(self.i18n.t("downloader.log_cancel_keep_normalization"), self.i18n.t("normalize"))

            for tmp_file, final_file in files_to_process:
                if not tmp_file or not final_file:
                    continue

                if not os.path.exists(tmp_file):
                    continue

                # ✅ Right destination (playlist vs single)
                if self.allow_playlist and self.playlist_dir:
                    final_file: str = os.path.join(
                        self.playlist_dir,
                        os.path.basename(final_file)
                    )

                os.makedirs(os.path.dirname(final_file), exist_ok=True)

                try:
                    shutil.move(tmp_file, final_file)

                    if self.file_finished_hook:
                        self.file_finished_hook(final_file)

                except OSError:
                    pass

            if self.keep_original_file:
                self._move_videos_from_tmp()

            return

        if not tmp_dir:
            return

        self._log(f"{self.i18n.t('downloader.log_files_collected')} {len(files_to_process)}", self.i18n.t("normalize"))

        if not files_to_process:
            self._log(self.i18n.t("downloader.log_not_files_to_process"), self.i18n.t("normalize"))

            return

        # ===============================
        # 🔹 Audio normalization loop
        # ===============================
        for index, (tmp_file, final_file) in enumerate(files_to_process, start=1):
            if not tmp_file or not final_file:
                continue

            tmp_file: str = os.path.abspath(tmp_file)
            final_file: str = os.path.abspath(final_file)

            if self.allow_playlist and self.playlist_dir:
                final_file: str = os.path.join(
                    self.playlist_dir,
                    os.path.basename(final_file)
                )

            if not os.path.exists(tmp_file):
                self._log(f"{self.i18n.t('downloader.log_not_files_found')} {tmp_file}", self.i18n.t("normalize"))

                continue

            if final_file in self.canceled_files:
                self._log(f"{self.i18n.t('downloader.log_ignore_canceled')} {tmp_file}", self.i18n.t("normalize"))

                continue

            if any(final_file.startswith(os.path.abspath(b)) for b in self.blocked_files):
                self._log(f"{self.i18n.t('downloader.log_ignore_blocked')}: {final_file}", self.i18n.t("normalize"))

                try:
                    os.remove(tmp_file)

                except OSError:
                    pass

                continue

            if not tmp_file.lower().endswith(f".{self.audio_format.lower()}"):
                self._log(f"{self.i18n.t('downloader.log_ignore_extension')} {tmp_file}", self.i18n.t("normalize"))

                os.makedirs(os.path.dirname(final_file), exist_ok=True)
                shutil.move(tmp_file, final_file)

                continue

            if is_normalized(final_file):
                self._log(f"{self.i18n.t('downloader.log_ignore_already_normalized')}: {final_file}", self.i18n.t("normalize"))

                continue

            self._log(f"({index}/{len(files_to_process)}) {self.i18n.t('downloader.log_normalize_init')} {os.path.basename(tmp_file)}", self.i18n.t("normalize"))

            try:
                Audio(tmp_file).normalize(target_lufs=-14.0)

                os.makedirs(os.path.dirname(final_file), exist_ok=True)

                shutil.move(tmp_file, final_file)

                self.generated_files.add(os.path.abspath(final_file))
                self.collected_files.append(os.path.abspath(final_file))

                mark_as_normalized(final_file, -14.0)

                self._log(f"OK → {final_file}", self.i18n.t("normalize"))

                if self.file_finished_hook:
                    self.file_finished_hook(final_file)

            except Exception as e:
                self._error(f"[{self.i18n.t('normalize_error')}] {tmp_file}: {e}")
                self._log(f"{tmp_file}: {e}", self.i18n.t("normalize_error"))

        # ===============================
        # 🔹 Move original videos
        # ===============================
        if self.keep_original_file:
            self._move_videos_from_tmp()

        self._log(self.i18n.t("downloader.log_normalize_finish"), self.i18n.t("normalize"))

    # ===============================
    # Move original videos from TMP
    # ===============================
    def _move_videos_from_tmp(self) -> None:
        """
        Move original video files from temporary folders to the final output folder.

        This method is executed only when `keep_original_file` is enabled.
        It scans temporary directories for video files and moves them to the
        appropriate destination without overwriting existing files.
        """

        search_dirs: list = [self.tmp_dir, self.tmp_playlist_dir]

        for base_dir in filter(None, search_dirs):
            if not os.path.exists(base_dir):
                continue

            for root, _, files in os.walk(base_dir):
                for file in files:
                    if not file.lower().endswith(".mp4"):
                        continue

                    tmp_video: str = os.path.join(root, file)
                    final_video: str = os.path.join(
                        self.playlist_dir if self.playlist_dir else self.output_path,
                        file
                    )

                    # Avoid overwriting existing files
                    if os.path.exists(final_video):
                        continue

                    os.makedirs(os.path.dirname(final_video), exist_ok=True)

                    try:
                        shutil.move(tmp_video, final_video)
                        self.generated_files.add(os.path.abspath(final_video))

                        self._log(f"{self.i18n.t('downloader.log_move_tmp_kept')} {final_video}", self.i18n.t("video"))

                    except Exception as e:
                        self._error(f"[{self.i18n.t('video_error')}] {tmp_video}: {e}")
                        self._log(f"{tmp_video}: {e}", self.i18n.t("video_error"))

    # ===============================
    # Cleanup Methods
    # ===============================
    def _cleanup_files(self) -> None:
        """
        Remove temporary and intermediate files generated during the download process.

        This method performs global cleanup of partial files, deletes canceled files,
        and removes intermediate or unsupported files based on the current settings.
        """

        allowed_exts: set = {f".{self.audio_format.lower()}"}

        if self.keep_original_file:
            allowed_exts.add(".mp4")

        # =========================
        # 0️⃣ Global cleanup of .part files
        # =========================
        search_dirs: set = set(filter(None, [
            self.output_path,
            self.tmp_dir,
            self.tmp_playlist_dir,
        ]))

        for base_dir in search_dirs:
            if not os.path.isdir(base_dir):
                continue

            for root, _, files in os.walk(base_dir):
                for file in files:
                    if file.endswith(".part"):
                        part_path: str = os.path.join(root, file)

                        try:
                            os.remove(part_path)

                            self._log(f".part {self.i18n.t('downloader.log_cleanup')} {part_path}", self.i18n.t("cleanup"))

                        except Exception as e:
                            self._log(f"{self.i18n.t('downloader.log_error_cleanup')} {part_path} — {e}", self.i18n.t("error_level"))

        # =========================
        # 1️⃣ Remove canceled files
        # =========================
        self._delete_canceled_files()

        # =========================
        # 2️⃣ State-based cleanup
        # =========================
        for file_path in list(self.generated_files):
            if not file_path or not os.path.exists(file_path):
                self.generated_files.discard(file_path)

                continue

            if file_path in self.blocked_files:
                continue

            filename: str = os.path.basename(file_path)
            ext: str = os.path.splitext(filename)[1].lower()

            # Remove yt-dlp intermediate files
            if YTDLP_INTERMEDIATE_RE.search(filename):
                try:
                    os.remove(file_path)

                    self._log(f"{self.i18n.t('downloader.log_cleanup_intermediate')} {file_path}", self.i18n.t("cleanup"))

                except OSError as e:
                    self._log(f"{self.i18n.t('downloader.log_error_cleanup_intermediate')} {file_path} — {e}", self.i18n.t("error_level"))

                self.generated_files.discard(file_path)
                continue

            # Remove files with extensions not allowed
            if ext not in allowed_exts:
                try:
                    os.remove(file_path)
                    self._log(f"{self.i18n.t('downloader.log_cleanup_ext_not_allowed')} {file_path}", self.i18n.t("cleanup"))

                except OSError as e:
                    self._log(f"{self.i18n.t('downloader.log_error_cleanup_remove')} {file_path} — {e}", self.i18n.t("error_level"))

                self.generated_files.discard(file_path)

    def _delete_canceled_files(self) -> None:
        """
        Delete files that were explicitly canceled by the user.

        This method retries deletion multiple times to handle file locks
        or delayed release by the operating system.
        """

        for file_path in list(self.canceled_files):
            time.sleep(2)

            for attempt in range(5):
                if not os.path.exists(file_path):
                    break

                try:
                    os.remove(file_path)

                    self._log(f"{self.i18n.t('downloader.log_delete_canceled')} {file_path}",self.i18n.t("cancel_level"))
                    break

                except PermissionError:
                    time.sleep(0.5)

            else:
                self._log(f"{self.i18n.t('downloader.log_error_delete_canceled')} {file_path}", self.i18n.t("cancel_level"))

            self.canceled_files.remove(file_path)

    def pause(self) -> None:
        """
        Pause the active download.

        This method saves the current state and blocks progress execution
        until the download is resumed.
        """

        if not self._download_active:
            return

        self.paused: bool = True

        if self._download_active:
            self.save_state(paused=self.paused)

        self._set_status(self.i18n.t("downloader.status_pause"))
        self._log(self.i18n.t("downloader.log_pause"), self.i18n.t("pause_level"))

        self.pause_event.clear()

    def resume(self) -> None:
        """
        Resume a previously paused download.

        Clears saved state and re-enables progress execution.
        """

        self.paused: bool = False
        self._clear_state()

        self._set_status(self.i18n.t("downloader.status_resume"))
        self._log(self.i18n.t("downloader.log_resume"), self.i18n.t("resume_level"))

        self.pause_event.set()

    # ===============================
    # State management
    # ===============================
    def save_state(self, paused: bool = False) -> None:
        """
        Save the current downloader state to a JSON file.

        This method always writes a valid and consistent state representation.

        :param paused: Indicates whether the download is paused
        :type paused: bool
        """

        # Never save an invalid state
        if not self.source_url and not self.selected_entries:
            self._log(self.i18n.t("downloader.log_save_state_invalid"), self.i18n.t("state"))

            return

        # Determine current mode
        if self.allow_playlist:
            mode: str = "playlist"

        else:
            mode: str = "single"

        playlist_selection: Optional[list[dict]] = None

        if mode == "playlist":
            playlist_selection = [
                {
                    "id": e.get("id"),
                    "title": e.get("title"),
                    "playlist_title": e.get("playlist_title")
                }
                for e in self.selected_entries
                if e.get("id")
            ]

        # Build final state payload
        state: dict = {
            "mode": mode,
            "url": self.source_url,
            "output_path": self.output_path,
            "audio_format": self.audio_format,
            "quality": self.quality,
            "resolution": self.resolution,
            "allow_playlist": self.allow_playlist,
            "keep_original": self.keep_original_file,
            "normalize_enabled": self.normalize_enabled,
            "paused": paused,
            "playlist_selection": playlist_selection
        }

        with open(self.STATE_FILE, "w", encoding="utf-8") as f:
            json.dump(state, f, indent=2, ensure_ascii=False)

        self._log(
            f"{self.i18n.t('downloader.log_save_state')} "
            f"({self.i18n.t('paused')}={paused}, {self.i18n.t('mode')}={mode}): "
            f"{self.STATE_FILE}",
            self.i18n.t("state")
        )

    def _clear_state(self) -> None:
        """
        Clear the persisted downloader state file.
        """

        if os.path.exists(self.STATE_FILE):
            os.remove(self.STATE_FILE)

            self._log(
                f"{self.i18n.t('downloader.log_clear_state')} {self.STATE_FILE}",
                self.i18n.t("state")
            )

    def save_state_on_close(self) -> None:
        """
        Save downloader state when the application is closing.

        This method is used by the UI layer to persist progress if
        a download is active or paused.
        """

        if self._download_active or self.paused:
            self.save_state(paused=True)

    # ===============================
    # Normalization helper
    # ===============================
    def _collect_files_for_normalize(self) -> List[Tuple[str, str]]:
        """
        Collect audio files from TMP folder and map them to final destination paths.

        :return: List of tuples containing (temporary_file_path, final_file_path)
        :rtype: List[Tuple[str, str]]
        """

        files: List[Tuple[str, str]] = []

        # TMP directory must exist to collect files
        if not self.tmp_dir or not os.path.exists(self.tmp_dir):
            return files

        # Walk through TMP directory recursively
        for root, _, filenames in os.walk(self.tmp_dir):
            for name in filenames:
                # Only collect files matching the selected audio format
                if not name.lower().endswith(f".{self.audio_format.lower()}"):
                    continue

                tmp_file: str = os.path.join(root, name)

                # Calculate real final destination path preserving structure
                rel: str = os.path.relpath(tmp_file, self.tmp_dir)
                final_file: str = os.path.join(self.output_path, rel)

                files.append((tmp_file, final_file))

        return files

    @staticmethod
    def get_playlist_folder_name(info: dict) -> str:
        """
        Get sanitized playlist folder name from metadata.

        :param info: Playlist metadata dictionary
        :type info: dict
        :return: Sanitized playlist folder name
        :rtype: str
        """

        title: str = info.get("title", "Playlist")

        return sanitize_filename(title)

    # ===============================
    # Download decision
    # ===============================
    def _should_download(self, base_path: str) -> bool:
        """
        Decide whether a file should be downloaded again.

        :param base_path: Final file path without extension
        :type base_path: str
        :return: True if download is required, False otherwise
        :rtype: bool
        """

        audio_path: str = base_path + f".{self.audio_format.lower()}"
        video_path: str = base_path + ".mp4"

        audio_exists: bool = os.path.exists(audio_path)
        video_exists: bool = os.path.exists(video_path)

        # =====================================================
        # Normalize enabled
        # =====================================================
        if self.normalize_enabled:
            # Audio must exist to skip download
            if not audio_exists:
                return True

            try:
                normalized: bool = is_normalized(audio_path)

            except Exception as e:
                # Force download if LUFS validation fails
                self._log(f"ERROR: {str(e)}", self.i18n.t("error_level"))

                return True

            # Redownload if audio is not normalized
            if not normalized:
                return True

            # Ensure original video exists if required
            if self.keep_original_file and not video_exists:
                return True

            return False

        # =====================================================
        # Without normalization
        # =====================================================
        if not self.keep_original_file:
            return not audio_exists

        return not (audio_exists and video_exists)

    def _cleanup_empty_dirs(self, root: str) -> None:
        """
        Remove empty directories recursively.

        :param root: Root directory to clean
        :type root: str
        """

        if not root or not os.path.exists(root):
            return

        # Walk bottom-up to safely remove empty folders
        for current, dirs, files in os.walk(root, topdown=False):
            if not dirs and not files:
                try:
                    os.rmdir(current)
                    self._log(
                        f"{self.i18n.t('downloader.log_cleanup_empty')} {current}",
                        self.i18n.t("cleanup")
                    )

                except OSError:
                    pass

    def _cleanup_tmp_normalize(self) -> None:
        """
        Remove temporary normalization directory.
        """

        if self.tmp_dir and os.path.exists(self.tmp_dir):
            try:
                shutil.rmtree(self.tmp_dir)

                self._log(
                    f"{self.i18n.t('downloader.log_cleanup_tmp_normalize')} {self.tmp_dir}",
                    self.i18n.t("cleanup")
                )

            except Exception as e:
                self._log(
                    f"{self.i18n.t('downloader.log_error_cleanup_tmp_normalize')} {e}",
                    self.i18n.t("error_level")
                )

    # ===============================
    # Utility / helper methods
    # ===============================
    def _log(self, message: str, level: str = "INFO") -> None:
        """
        Internal logging helper.

        :param message: Message to be logged
        :type message: str
        :param level: Log severity level
        :type level: str
        """

        from datetime import datetime

        # Translate default INFO level
        if level == "INFO":
            level: str = self.i18n.t("info")

        timestamp: str = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
        entry: str = f"[{timestamp}] {level}: {message}\n"

        if self.log_hook:
            self.log_hook(entry)

    def log(self, message: str, level: str = "INFO") -> None:
        """
        Public logging wrapper.

        :param message: Message to be logged
        :type message: str
        :param level: Log severity level
        :type level: str
        """

        if level == "INFO":
            level: str = self.i18n.t("info")

        self._log(message, level)

    def  _set_status(self, message: str) -> None:
        """
        Internal status update helper.

        :param message: Status message
        :type message: str
        """

        if self.status_hook:
            self.status_hook(message)

    def _error(self, message: str) -> None:
        """
        Internal error reporting helper.

        :param message: Error message
        :type message: str
        """

        if self.error_hook:
            self.error_hook(message)

    # ===============================
    # Post-download / cancel cleanup
    # ===============================
    def _cleanup_after_cancel_or_finished(self) -> None:
        """
        Perform cleanup after download completion or cancellation.
        """

        # Remove TMP playlist directory
        if self.tmp_playlist_dir and os.path.exists(self.tmp_playlist_dir):
            try:
                shutil.rmtree(self.tmp_playlist_dir)
                self._log(
                    f"{self.i18n.t('downloader.log_cleanup_after_cancel_finished_folder')} {self.tmp_playlist_dir}",
                    self.i18n.t("cleanup")
                )

            except Exception as e:
                self._log(
                    f"{self.i18n.t('downloader.log_error_cleanup_after_cancel_finished')} {e}",
                    self.i18n.t("error_level")
                )

        # Cleanup generated and intermediate files
        self._cleanup_files()

        # Remove normalization TMP folder
        self._cleanup_tmp_normalize()

        # Clear persisted state
        self._clear_state()

        # Remove empty output directories
        self._cleanup_empty_dirs(self.output_path)

        self._download_active = False

        # Final status update
        if self.cancel_requested:
            self._set_status(self.i18n.t("downloader.status_canceled"))
            self._log(
                self.i18n.t("downloader.log_cleanup_after_cancel_finished"),
                self.i18n.t("cancel_level")
            )

        else:
            self._set_status(self.i18n.t("downloader.status_canceled_finish"))
            self._log(
                self.i18n.t("downloader.log_cleanup_after_cancel_finish"),
                self.i18n.t("done")
            )

    def normalize_move_and_clean(self) -> None:
        """
        Execute normalization, cleanup, and final file movement
        based on current configuration flags.
        """

        if self.normalize_enabled:
            self._normalize_files()

        self._cleanup_files()

        # Move files from TMP playlist directory to final destination
        if self.tmp_playlist_dir and os.path.exists(self.tmp_playlist_dir):
            os.makedirs(self.playlist_dir, exist_ok=True)

            for f in os.listdir(self.tmp_playlist_dir):
                shutil.move(
                    os.path.join(self.tmp_playlist_dir, f),
                    os.path.join(self.playlist_dir, f)
                )

            shutil.rmtree(self.tmp_playlist_dir, ignore_errors=True)

    def skip_current_item(self, reason: str = "") -> None:
        """
        Skip the current item and continue processing.

        :param reason: Optional skip reason
        :type reason: str
        """

        video_id: str = (
            self.current_info.get("id")
            if self.current_info else "unknown"
        )

        msg: str = f"⏭️ Skipping video {video_id}"

        if reason:
            msg += f" — {reason}"

        self._log(msg, self.i18n.t("warning"))

        # Reset authentication retry state
        self.failed_video_id = None

        return

    def _apply_cookies_if_needed(self) -> None:
        """
        Apply browser cookies to yt-dlp options if configured.
        """

        if self.cookies_from_browser:
            self.ydl_opts["cookiesfrombrowser"] = (self.cookies_from_browser,)
        else:
            self.ydl_opts.pop("cookiesfrombrowser", None)

    @staticmethod
    def _is_auth_error(msg: str) -> bool:
        """
        Check if error message indicates authentication failure.

        :param msg: Error message
        :type msg: str
        :return: True if authentication error detected
        :rtype: bool
        """

        msg: str = msg.lower()

        return any(marker in msg for marker in AUTH_ERROR_MARKERS)

    def _try_next_browser_cookie(self) -> bool:
        """
        Try next browser cookie source for authentication.

        :return: True if retry is possible, False otherwise
        :rtype: bool
        """

        if self._auth_retry_index >= len(self._auth_retry_browsers):
            return False

        browser = self._auth_retry_browsers[self._auth_retry_index]
        self._auth_retry_index += 1

        self.cookies_from_browser = browser
        self._retrying_auth = True

        self._log(
            f"{self.i18n.t('downloader.log_retrying')} {browser}",
            self.i18n.t("auth")
        )
        return True

    def get_info(self, *, flat: bool = False) -> dict:
        """
        Extract and cache yt-dlp metadata.

        :param flat: If True, extract flat metadata only
        :type flat: bool
        :return: Extracted information dictionary
        :rtype: dict
        """

        if self._cached_info is not None and self._cached_flat == flat:
            return self._cached_info

        self._build_ydl_opts()

        opts = dict(self.ydl_opts)

        if flat:
            opts.update({
                "skip_download": True,
                "extract_flat": True,
                "ignoreerrors": True
            })

        with yt_dlp.YoutubeDL(opts) as ydl:
            info: dict = ydl.extract_info(self.url, download=False)

        if info and info.get("_type") == "url":
            info: dict = ydl.extract_info(info["url"], download=False)

        self._cached_info = info
        self._cached_flat = flat

        return info

    def _apply_browser_cookie(self) -> bool:
        """
        Apply cookiesfrombrowser using the current authentication retry index.

        Returns False if no more browser cookie sources are available.

        :return: True if a browser cookie was applied, False otherwise
        :rtype: bool
        """

        # No more browsers available for retry
        if self._auth_retry_index >= len(self._auth_retry_browsers):
            return False

        browser = self._auth_retry_browsers[self._auth_retry_index]

        # Set current browser as cookie source
        self.cookies_from_browser = browser

        self._log(
            f"{self.i18n.t('downloader.log_retrying')}: {browser}",
            self.i18n.t("auth")
        )

        # Advance retry index
        self._auth_retry_index += 1

        return True

    def _reset_auth_retry(self) -> None:
        """
        Reset authentication retry state.
        """

        self._auth_retry_index = 0
        self._retrying_auth = False
        self.cookies_from_browser = None

    def retry_current_item(self) -> None:
        """
        Retry the current video using browser cookie fallback.

        This method is called after an authentication-required error.
        """

        # Prevent concurrent authentication retries
        if self._retrying_auth:
            return

        self._retrying_auth = True

        # Try next browser cookie source
        if not self._apply_browser_cookie():
            self._log(self.i18n.t("downloader.log_retrying_failed"), self.i18n.t("auth"))
            raise RuntimeError("AUTH_FAILED")

        # Rebuild yt-dlp options with cookies enabled
        self._build_ydl_opts()

        if self.cookies_from_browser:
            self.ydl_opts["cookiesfrombrowser"] = (
                self.cookies_from_browser,
                None,
                None,
                None,
            )

        # Retry the exact same item
        if self.current_info:
            with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
                ydl.process_ie_result(self.current_info, download=True)

        self._retrying_auth = False

    def _extract_light_info(self, url: str) -> dict:
        """
        Perform fast, non-authenticated metadata extraction.

        Cached. Safe for playlists, mixes, and selection UI.

        :param url: Source URL
        :type url: str
        :return: Extracted metadata dictionary
        :rtype: dict
        """

        # Return cached result if available
        if url in self._extract_cache:
            return self._extract_cache[url]

        ydl_opts = {
            "quiet": True,
            "skip_download": True,
            "extract_flat": True,
            "nocheckcertificate": True,
            "ignoreerrors": True,
        }

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info: dict = ydl.extract_info(url, download=False)

                # Resolve URL indirections
                if info and info.get("_type") == "url":
                    info = ydl.extract_info(info["url"], download=False)

        except Exception as e:
            # Log internally but don't break the flow
            self._log(f"Failed to extract video info: {str(e)}", level=self.i18n.t("error_level"))
            info = {
                "_type": "video",
                "title": "[Restricted video]",
                "__restricted__": "unknown",
                "id": None,
            }

        # Guarantee always return a dictionary
        if not isinstance(info, dict):
            info = {
                "_type": "video",
                "title": "[Restricted video]",
                "__restricted__": "unknown",
                "id": None,
            }

        self._extract_cache[url] = info

        return info

    @staticmethod
    def _normalize_playlist_entries(info: dict) -> list:
        """
        Normalize playlist entries for selection UI.

        Ensures presence of id, title, duration, URL, and restriction flag.

        :param info: Raw playlist metadata
        :type info: dict
        :return: Normalized list of playlist entries
        :rtype: list
        """

        entries: List[dict] = []

        for e in info.get("entries", []):
            if not e:
                continue

            entries.append({
                "id": e.get("id"),
                "title": e.get("title") or "Unavailable",
                "duration": e.get("duration"),
                "url": e.get("url"),
                "is_restricted": e.get("availability") in (
                    "private",
                    "needs_auth",
                    "subscriber_only"
                ) or e.get("live_status") == "not_live",
            })

        return entries

    def notify_restricted(self, msg: str) -> None:
        """
        Notify UI and logs about restricted or unavailable content.

        :param msg: Restriction message
        :type msg: str
        """

        self._log(msg, self.i18n.t("skip"))

        if self.status_hook:
            self.status_hook(self.i18n.t("downloader.status_notify_restricted"))

        if not self._alerted_private:
            self._alerted_private = True
            self._error(self.i18n.t("downloader.error_notify_restricted"))

    def _cleanup_orphan_tmps(self) -> None:
        """
        Remove leftover TMP folders from previous interrupted sessions.

        Safe to call during application startup.
        """

        base = self.output_path

        for name in os.listdir(base):
            if name.startswith(".tmp_playlist_") or name == "temp_normalize":
                path = os.path.join(base, name)

                try:
                    shutil.rmtree(path)
                    self._log(f"{self.i18n.t('downloader.log_cleanup_orphan_tmps')} {path}", self.i18n.t("cleanup"))

                except Exception as e:
                    self._log(f"{self.i18n.t('downloader.log_error_cleanup_orphan_tmps')} {path} — {e}", self.i18n.t("error_level"))

    def _build_format_string(self) -> str:
        """
        Build yt-dlp format selection string based on resolution and mode.

        :return: yt-dlp format string
        :rtype: str
        """

        resolution_map = {
            "Auto": None,
            "480p": 480,
            "720p": 720,
            "1080p": 1080,
        }

        h = resolution_map.get(self.resolution)

        # Audio-only mode
        if not self.keep_original_file and self.audio_format:
            return "bestaudio/best"

        # Video + audio with resolution fallback
        if h:
            return (
                f"(bestvideo[height<={h}]/bestvideo)+"
                "bestaudio/best"
            )

        return "bestvideo+bestaudio/best"
