# core/downloader.py

import json
import os
import re
import shutil
import threading
import time
import yt_dlp
import yt_dlp.utils

from typing import Optional, Callable, List, Tuple, Any, TypedDict

from core.ydl_logger import YDLLogger
from core.audio import Audio
from utils.helpers import safe_float
from utils.paths import get_ffmpeg_path
from utils.audio_tags import is_normalized, mark_as_normalized
from utils.sanitize import sanitize_filename
from i18n.manager import I18nManager


# Regex to detect intermediate files generated by yt-dlp
YTDLP_INTERMEDIATE_RE = re.compile(r"\.f\d+\.(webm|mp4|mkv|m4a|aac|opus)(\.part)?$", re.IGNORECASE)

# Main audio/video extensions
MAIN_EXTS = {".mp3", ".wav", ".flac", ".m4a", ".aac", ".opus", ".mp4", ".mkv", ".webm"}

BROWSER_FALLBACK: list = ["chrome", "edge", "firefox", "opera"]

AUTH_ERROR_MARKERS = (
    "this video is private",
    "sign in",
    "age-restricted",
    "sign in to confirm your age",
    "members-only",
    "members-only content",
    "login required",
    "private video",
    "this video is unavailable"
)


def _safe_dict(value) -> dict:
    return value if isinstance(value, dict) else {}


class Downloader:
    """
    Handles YouTube audio/video downloads using yt-dlp, with support for:
        - Playlist downloads
        - Audio normalization (LUFS)
        - Pause/resume
        - Cancel
        - Keeping original video files
        - Progress and status hooks for UI integration

    Hooks (all optional):
        - progress_hook(percent: float, playlist_index: int, playlist_count: int, status_text: str)
        - status_hook(message: str)
        - file_finished_hook(file_path: str)
        - error_hook(error_message: str)
        - log_hook(log_message: str)
    """

    def __init__(
        self,
        url: str,
        output_path: str,
        audio_format: str = "mp3",
        quality: str = "192",
        resolution: str = "Auto",
        allow_playlist: bool = False,
        keep_original_file: bool = False,
        normalize_enabled: bool = False,
        progress_hook: Optional[Callable[..., None]] = None,
        status_hook: Optional[Callable[[str], None]] = None,
        file_finished_hook: Optional[Callable[[str], None]] = None,
        error_hook: Optional[Callable[[str], None]] = None,
        log_hook: Optional[Callable[[str], None]] = None,
        confirm_keep_hook: Optional[Callable[[str], bool]] = None,
        state_file: Optional[str] = None,
        language: Optional[str] = "en-US",
    ) -> None:
        # ===============================
        # Core configuration
        # ===============================
        self.language: str = language
        self.i18n: I18nManager = I18nManager(language=self.language)

        self.pending_pause: bool = None
        self.source_url: str = url
        self.url = url
        self.output_path = output_path
        self.audio_format = audio_format
        self.quality = quality
        self.resolution = resolution
        self.allow_playlist = allow_playlist
        self.keep_original_file = keep_original_file
        self.normalize_enabled = normalize_enabled

        # ===============================
        # Hooks for UI/controller callbacks
        # ===============================
        self.progress_hook = progress_hook
        self.status_hook = status_hook
        self.file_finished_hook = file_finished_hook
        self.error_hook = error_hook
        self.log_hook = log_hook
        self.confirm_keep_hook = confirm_keep_hook

        # ===============================
        # Internal state
        # ===============================
        self.ffmpeg_path = get_ffmpeg_path()
        self.generated_files: set[str] = set()
        self.canceled_files: set[str] = set()
        self.files_to_normalize: List[Tuple[str, str]] = []
        self.collected_files: list[str] = []
        self.tmp_dir: Optional[str] = None
        self.tmp_playlist_dir: Optional[str] = None
        self.playlist_dir: Optional[str] = None
        self.playlist_index: Optional[int] = None
        self.playlist_count: Optional[int] = None
        self._cached_info: Optional[dict] = None
        self._cached_flat: bool = False
        self._extract_cache: dict = {}

        self.cancel_requested: bool = False
        self.cancel_after_current: bool = False
        self.keep_after_cancel: bool = False

        self.cookies_from_browser: Optional[str] = None
        self.browser_retry_index: int = 0

        self.paused: bool = False
        self.pause_event: threading.Event = threading.Event()
        self.pause_event.set()  # Not paused by default

        self.selected_entries: Optional[List[dict]] = None
        self.blocked_files: set[str] = set()
        self.canceled_titles: set[str] = set()

        self._download_active: bool = False
        self.STATE_FILE: Optional[str] = state_file or os.path.join(self.output_path, ".download_state.json")

        self.ydl_opts: dict[str, Any] = {}

        self.current_info: Optional[dict] = None
        self.failed_video_id: str | None = None

        # ===============================
        # Manual playlist selection
        # ===============================
        self._auth_retry_index: int = 0
        self._retrying_auth: bool = False

        self._auth_retry_browsers: list[str] = [
            "edge",
            "chrome",
            "firefox",
            "opera"
        ]

        self._extra_ydl_opts: dict = {}

        self._restricted_alert_shown: bool = False

        # ===============================
        # Manual playlist selection
        # ===============================
        self.playlist_title: str = None
        self.selected_entries = None
        self.is_manual_selection = False

        self._alerted_private: bool = False
        self._logged_resolution: bool = False

        # ===============================
        # Internal thread safety lock
        # ===============================
        self._lock = threading.Lock()

    # ===============================
    # Public methods
    # ===============================
    def start(self) -> None:
        self._download_active = True
        self._logged_resolution = False

        # 🔥 CLEAN ORPHAN TMPs FROM PREVIOUS CRASH
        self._cleanup_orphan_tmps()

        try:
            # =============================
            # RESET STATE
            # =============================
            self.tmp_playlist_dir = None
            self.playlist_dir = None
            self.playlist_index = None
            self.playlist_count = None

            self._prepare_dirs()

            # =============================
            # BUILD BASE OPTS (NO AUTH)
            # =============================
            self._build_ydl_opts()
            self.ydl_opts.pop("cookiesfrombrowser", None)

            # =============================
            # EXTRACT INFO (LIGHT, NO AUTH)
            # =============================
            if self.selected_entries:
                self._log(
                    f"{self.i18n.t('downloader.log_selected_entries')} ({len(self.selected_entries)} item(s))",
                    "FLOW"
                )

                info = {
                    "_type": "playlist",
                    "title": self.playlist_title or "Playlist",
                    "entries": self.selected_entries,
                }

            else:
                if not self.url:
                    raise RuntimeError("No URL provided")

                info = self._extract_light_info(self.url)

                if not info:
                    raise RuntimeError("[Restrict Video]: Failed to extract video metadata")

                # cache only if playlist
                if info.get("_type") == "playlist" or "entries" in info:
                    self._cached_info = info
                    self._cached_flat = True

            if not info:
                raise RuntimeError("Failed to extract info")

            is_playlist = info.get("_type") == "playlist" or "entries" in info

            # =============================
            # PLAYLIST
            # =============================
            if self.allow_playlist and is_playlist:
                self._download_playlist(info)
                return

            # =============================
            # SINGLE (FORCED)
            # =============================
            self.allow_playlist = False

            # 🔥 ensure full info for single, but NO re-extract if already resolved
            info = self.get_info(flat=False)

            self._download_single(info)

        except Exception as e:
            msg = str(e)

            self._error(msg)
            self._log(f"{self.i18n.t('downloader.log_error_download_failed')} {msg}", "ERROR")

        finally:
            if not self.paused:
                self._finalize_download()

    # ===============================
    # Internal methods (download flow)
    # ===============================
    def _prepare_dirs(self) -> None:
        """Create necessary output directories."""

        os.makedirs(self.output_path, exist_ok=True)

        self.generated_files.clear()
        self.canceled_files.clear()
        self.collected_files.clear()
        self.files_to_normalize.clear()

        self._set_status(self.i18n.t("downloader.status_prepare_dirs"))

        self._log(self.i18n.t("downloader.log_prepare_dirs"), "START")

    def _build_ydl_opts(self) -> None:
        """
        Build yt-dlp options dict according to current settings:
        playlist, normalization, format, quality, etc.
        """

        base_output = self.output_path

        # ==============================
        # 🔹 NORMALIZING IS AN ABSOLUTE PRIORITY
        # ==============================
        if self.normalize_enabled:
            self.tmp_dir = os.path.join(base_output, "temp_normalize")
            os.makedirs(self.tmp_dir, exist_ok=True)
            output_dir = self.tmp_dir

        # ===============================
        # 🔹 NO NORMALIZE → you can use playlist's tmp
        # ===============================
        elif self.allow_playlist and self.tmp_playlist_dir:
            output_dir = self.tmp_playlist_dir

        # =============================
        # 🔹 NO NORMALIZE AND NO PLAYLIST
        # =============================
        else:
            output_dir = base_output

        self.ydl_opts = {
            "format": self._build_format_string(),
            "ffmpeg_location": self.ffmpeg_path,

            "outtmpl": os.path.join(
                output_dir,
                "%(title)s [%(id)s].%(ext)s"
            ),

            "noplaylist": not self.allow_playlist,
            "merge_output_format": "mp4",
            "external_downloader_args": ["-nostdin"],
            "keepvideo": self.keep_original_file,

            "progress_hooks": [self._progress_hook],
            "postprocessor_hooks": [self._postprocessor_hook],

            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": self.audio_format,
                    "preferredquality": self.quality,
                }
            ],

            "restrictfilenames": True,
            "nopart": False,
            "quiet": True,
            "logger": YDLLogger(self),
            "no_warming": True,
            "ignoreerrors": True,
            "continuedl": True
        }

        self.ydl_opts.update(self._extra_ydl_opts)

        if self._retrying_auth or self.cookies_from_browser:
            self.ydl_opts["extractor_args"] = {
                "youtube": {
                    "player_client": ["web", "tv_embedded"]
                }
            }
        else:
            self.ydl_opts.pop("extractor_args", None)

    # ===============================
    # Internal download methods
    # ===============================
    def _download_playlist(self, info: dict) -> None:
        """
        Handle playlist download.
        Respects manual selection, avoids re-expansion and supports auth retry.
        """

        playlist_name = sanitize_filename(
            self.playlist_title
            or info.get("title")
            or "Playlist"
        )

        self.playlist_dir = os.path.join(self.output_path, playlist_name)
        os.makedirs(self.playlist_dir, exist_ok=True)

        self.tmp_playlist_dir = os.path.join(
            self.output_path,
            f".tmp_playlist_{playlist_name}_{int(time.time())}"
        )
        os.makedirs(self.tmp_playlist_dir, exist_ok=True)

        # -------------------------------
        # Build base options
        # -------------------------------
        self._build_ydl_opts()

        if not self.normalize_enabled:
            self.ydl_opts["outtmpl"] = os.path.join(
                self.tmp_playlist_dir,
                "%(title)s [%(id)s].%(ext)s"
            )

        # -------------------------------
        # Resolve manual selection
        # -------------------------------
        selected_ids = None
        if self.selected_entries:
            selected_ids = {
                e.get("id") for e in self.selected_entries if e and e.get("id")
            }

        entries_to_download: list = []

        # -------------------------------
        # FILTER PHASE (no download here)
        # -------------------------------
        for entry in info.get("entries", []):
            if not entry:
                continue

            video_id = entry.get("id")
            if not video_id:
                continue

            if selected_ids and video_id not in selected_ids:
                continue

            title = sanitize_filename(entry.get("title", "untitled"))
            final_base = os.path.join(
                self.playlist_dir,
                f"{title} [{video_id}]"
            )

            if self._should_download(final_base):
                entries_to_download.append(entry)
            else:
                self._log(f"{self.i18n.t('downloader.log_skipping_cached')} {title}", "CACHE")

        if not entries_to_download:
            self._log(self.i18n.t("downloader.log_error_not_entries"), "CACHE")

            shutil.rmtree(self.tmp_playlist_dir, ignore_errors=True)

            return

        # -------------------------------
        # DOWNLOAD PHASE (NO RE-EXTRACT)
        # -------------------------------
        self._apply_cookies_if_needed()

        for entry in entries_to_download:
            self._reset_auth_retry()
            self.current_info = entry
            self.failed_video_id = entry.get("id")

            while True:
                try:
                    self._build_ydl_opts()
                    self._apply_cookies_if_needed()

                    with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
                        # 🔥 ONE VIDEO ONLY — no playlist expansion
                        ydl.process_ie_result(entry, download=True)

                    break  # ✅ success

                except Exception as e:
                    msg = str(e)

                    if self._is_auth_error(msg):
                        if self._try_next_browser_cookie():
                            continue

                        title = entry.get("title", self.i18n.t("downloader.unknown_video_title"))

                        self._log(
                            f"{self.i18n.t('downloader.log_error_restricted_private')} {title}",
                            "SKIP"
                        )

                        # 🔔 notify UI ONCE
                        self._set_status(f"{self.i18n.t('downloader.status_skipped_restricted')} {title}")

                        if not self._restricted_alert_shown:
                            self._restricted_alert_shown: bool = True
                            self._error(self.i18n.t("downloader.error_download_playlist"))

                        break

                    raise

    def _download_single(self, info: dict) -> None:
        """
        Handle single video download (no playlist).
        Supports auth retry and instant start.
        """

        self._build_ydl_opts()

        video_id = info.get("id")
        title = sanitize_filename(info.get("title", self.i18n.t("downloader.unknown_video_title")))

        if video_id:
            base_path = os.path.join(
                self.output_path,
                f"{title} [{video_id}]"
            )

            if not self._should_download(base_path):
                self._log({self.i18n.t("downloader.log_not_should_download")}, "CACHE")

                return

        # -------------------------------
        # Prepare retry state
        # -------------------------------
        self._reset_auth_retry()
        self.current_info = info
        self.failed_video_id = info.get("id")

        while True:
            try:
                self._build_ydl_opts()
                self._apply_cookies_if_needed()

                with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
                    ydl.process_ie_result(info, download=True)

                break  # ✅ success

            except Exception as e:
                msg = str(e)

                if self._is_auth_error(msg):
                    if self._try_next_browser_cookie():
                        continue

                    self._log(
                        f"{self.i18n.t('downloader.log_error_auth_failed')} {info.get('id')}",
                        "SKIP"
                    )

                    return

                raise

    def _finalize_download(self) -> None:
        """
        Actions to finalize download after yt-dlp completes.
        Handles normalization, moving TMP files, cleaning state.
        """

        # =============================
        # CANCELLED + KEEP
        # =============================
        if self.cancel_requested and self.keep_after_cancel:
            self._log(self.i18n.t("downloader.log_cancel_keep"), "CANCEL")

            self.normalize_move_and_clean()

            # 🔥 SINGLE + NORMALIZE → move everything from the temp folder to normalize
            if (
                    self.normalize_enabled
                    and not self.allow_playlist
                    and self.tmp_dir
                    and os.path.exists(self.tmp_dir)
            ):
                for f in os.listdir(self.tmp_dir):
                    src = os.path.join(self.tmp_dir, f)
                    dst = os.path.join(self.output_path, f)

                    if os.path.exists(dst):
                        continue

                    shutil.move(src, dst)

                shutil.rmtree(self.tmp_dir, ignore_errors=True)

            self._cleanup_after_cancel_or_finished()

            return

        # =============================
        # CANCELED WITHOUT KEEP
        # =============================
        if self.cancel_requested and not self.keep_after_cancel:
            self._log(self.i18n.t("downloader.log_cancel_no_keep"), "CANCEL")

            # 🔥 ERASE ONLY PMS
            if self.tmp_playlist_dir:
                shutil.rmtree(self.tmp_playlist_dir, ignore_errors=True)

            self._cleanup_after_cancel_or_finished()

            return

        # =============================
        # NORMAL FLOW
        # =============================
        if not self.paused:
            self.normalize_move_and_clean()

            self._cleanup_after_cancel_or_finished()

    # ===============================
    # Cancel method
    # ===============================
    def cancel(self, after_current: bool = False) -> None:
        """
        Cancel the download.

        :param after_current: If True, cancel after the current playlist item finishes.
        :type after_current: bool
        """

        self.pause_event.set()

        if after_current and self.allow_playlist:
            self.cancel_after_current: bool = True

            self._log(self.i18n.t("downloader.log_cancel_after_current"), "CANCEL")

        else:
            self.cancel_requested = True
            self.cancel_after_current: bool = False

            self._log(self.i18n.t("downloader.log_cancel_immediate"), "CANCEL")

    # ===============================
    # Hooks for yt-dlp
    # ==============================
    def _progress_hook(self, d: dict) -> None:
        """
        yt-dlp progress hook. Reports progress, handles cancel requests, tracks generated files.

        :param d: yt-dlp progress dictionary.
        :type d: dict
        """

        # 🔥 Apply deferred pause at first progress callback
        if self.pending_pause:
            self.pause_event.clear()
            self.pending_pause = False

        self.pause_event.wait()

        # Captures temporary files from yt-dlp
        for key in ("tmpfilename", "filename"):
            path: str = d.get(key)

            if path:
                self.generated_files.add(os.path.abspath(path))

        # ===============================
        # 1️⃣ Main files only
        # ===============================
        filename: str = d.get("filename") or d.get("tmpfilename")

        # Only show main file progress
        ext: str = os.path.splitext(filename or "")[1].lower()
        is_main_file: bool = ext in MAIN_EXTS

        if is_main_file and filename and hasattr(self, "audio_format") and self.audio_format:
            # Generates a nice display for logs (does not modify files)
            display_filename: str = os.path.basename(filename)
            display_filename: str = re.sub(r'\.f\d+\.', '.', display_filename)  # remove intermediary
            display_filename: str = os.path.splitext(display_filename)[0]  # remove original extension
            display_filename: str = f"{display_filename}.{self.audio_format.lower()}"

            status: str = d.get("status")
            playlist_index: str = d.get("playlist_index")
            playlist_count: str = d.get("playlist_count")

            if status == "downloading":
                info = d.get("info_dict") or {}

                if self.keep_original_file:
                    fmt = info.get("format")
                    height = info.get("height")
                    fps = info.get("fps")
                    vcodec = info.get("vcodec")

                    self._log(
                        f"{self.i18n.t('downloader.log_format_resolution')} {fmt} — {height}p @ {fps}fps — {vcodec}",
                        "INFO"
                    )
                    self._logged_resolution = True

                downloaded_bytes: float = safe_float(d.get("downloaded_bytes"))
                total_bytes: float = safe_float(d.get("total_bytes") or d.get("total_bytes_estimate"), 1)
                percent: float = (downloaded_bytes / total_bytes * 100) if total_bytes else 0.0
                speed: float = safe_float(d.get("speed"))
                eta: int = int(d.get("eta") or 0)

                downloaded_mb: float = downloaded_bytes / (1024 * 1024)
                total_mb: float = total_bytes / (1024 * 1024)

                status_text: str = f"{percent:5.1f}% — {downloaded_mb:.2f}/{total_mb:.2f} MB — " \
                                   f"{speed / 1024:.2f} KB/s — ETA {eta}s"

                if playlist_index and playlist_count:
                    idx = int(playlist_index)
                    total = int(playlist_count)
                    status_text = f"{idx:02d}/{total:02d} — {status_text}"

                if downloaded_bytes == 0:
                    self._log(f"{self.i18n.t('downloader.log_starting')} {display_filename}", "DOWNLOAD")

                self._log(f"{status_text}", "DOWNLOAD")

                if self.progress_hook:
                    self.progress_hook(percent, playlist_index, playlist_count, status_text)

            elif status == "finished":
                abs_path: str = os.path.abspath(filename)
                self.generated_files.add(abs_path)


                self._log(f"{display_filename}", "DONE")

                if self.progress_hook:
                    self.progress_hook(
                        100.0,
                        d.get("playlist_index"),
                        d.get("playlist_count"),
                        f"[DONE] {display_filename}"
                    )
        # ===============================
        # 2️⃣ Immediate Cancellation
        # ===============================
        if self.cancel_requested and not self.cancel_after_current:
            tmp_file: str = d.get("tmpfilename")

            if tmp_file and os.path.exists(tmp_file):
                try:
                    os.remove(tmp_file)
                    self._log(f"{self.i18n.t('downloader.log_remove_tmp')} {tmp_file}", "CANCEL")

                except Exception as e:
                    self._log(f"{self.i18n.t('downloader.log_error_remove_tmp')} {tmp_file} — {e}", "ERROR")

            raise yt_dlp.utils.DownloadError("Download canceled by user")

    def _postprocessor_hook(self, d: dict) -> None:
        """
        yt-dlp postprocessor hook.
        Tracks generated files and handles cancel after current item.
        """

        if d.get("status") != "finished":
            return

        info: dict = d.get("info_dict") or {}

        # ==============================
        # 🔁 RESET AUTH RETRY
        # ==============================
        self._auth_retry_index = 0
        self._retrying_auth = False
        self.cookies_from_browser = None

        possible_paths: list[str] = []

        # Collect possible generated paths
        for key in ("filepath", "filename", "_filename"):
            val = d.get(key) or info.get(key)
            if isinstance(val, str):
                possible_paths.append(val)

        requested = d.get("requested_downloads")
        if isinstance(requested, list):
            for item in requested:
                path = item.get("filepath") or item.get("filename")
                if path:
                    possible_paths.append(path)

        # Register generated files
        for path in possible_paths:
            abs_path = os.path.abspath(path)
            if os.path.exists(abs_path):
                self.generated_files.add(abs_path)

        # ==============================
        # Cancel after current item
        # ==============================
        if self.cancel_after_current:
            self.cancel_after_current = False

            keep = True
            main_file = possible_paths[-1] if possible_paths else None

            if main_file and os.path.exists(main_file):
                if self.confirm_keep_hook:
                    keep = self.confirm_keep_hook(main_file)

                if not keep:
                    self.canceled_files.add(os.path.abspath(main_file))

            self.keep_after_cancel = keep
            self.cancel_requested = True

            self._log(
                f"{self.i18n.t('downloader.log_cancel_wanna_keep')} {keep}",
                "CANCEL"
            )

        # ==============================
        # RESET AUTH RETRY (SUCCESS ONLY)
        # ==============================
        video_id = info.get("id")

        if self.current_info and video_id == self.current_info.get("id"):
            self._auth_retry_index = 0
            self._retrying_auth = False
            self._extra_ydl_opts.clear()
            self.cookies_from_browser = None

    # ===============================
    # Normalization
    # ===============================
    def _normalize_files(self) -> None:
        """
        Normalize audio files in the TMP folder to target LUFS (-14 dB).
        Moves normalized files to final output folder.
        """

        files_to_process: list = self._collect_files_for_normalize()
        tmp_dir: str = self.tmp_dir

        # 🔥 Canceled + Keep → only move files, no normalization
        if self.cancel_requested and self.keep_after_cancel:
            self._log(self.i18n.t("downloader.log_cancel_keep_normalization"), "NORMALIZE")

            for tmp_file, final_file in files_to_process:
                if not tmp_file or not final_file:
                    continue

                if not os.path.exists(tmp_file):
                    continue

                # ✅ Right destination (playlist vs single)
                if self.allow_playlist and self.playlist_dir:
                    final_file: str = os.path.join(
                        self.playlist_dir,
                        os.path.basename(final_file)
                    )

                os.makedirs(os.path.dirname(final_file), exist_ok=True)

                try:
                    shutil.move(tmp_file, final_file)

                    if self.file_finished_hook:
                        self.file_finished_hook(final_file)

                except OSError:
                    pass

                # 🔥 Move original videos, if necessary
            if self.keep_original_file:
                self._move_videos_from_tmp()

            return

        if not tmp_dir:
            return

        self._log(f"{self.i18n.t('downloader.log_files_collected')} {len(files_to_process)}", "NORMALIZE")

        if not files_to_process:
            self._log(self.i18n.t("downloader.log_not_files_to_process"), "NORMALIZE")

            return

        # ===============================
        # 🔹 Normalize audio
        # ===============================
        for index, (tmp_file, final_file) in enumerate(files_to_process, start=1):
            if not tmp_file or not final_file:
                continue

            tmp_file: str = os.path.abspath(tmp_file)
            final_file: str = os.path.abspath(final_file)

            # ✅ Right destination (playlist vs single)
            if self.allow_playlist and self.playlist_dir:
                final_file: str = os.path.join(
                    self.playlist_dir,
                    os.path.basename(final_file)
                )

            # ❌ file does not exist
            if not os.path.exists(tmp_file):
                self._log(f"{self.i18n.t('downloader.log_not_files_found')} {tmp_file}", "NORMALIZE")

                continue

            # ❌ canceled file
            if final_file in self.canceled_files:
                self._log(f"{self.i18n.t('downloader.log_ignore_canceled')} {tmp_file}", "NORMALIZE")

                continue

            # ❌ locked folder or file
            if any(final_file.startswith(os.path.abspath(b)) for b in self.blocked_files):
                self._log(f"{self.i18n.t('downloader.log_ignore_blocked')}: {final_file}", "NORMALIZE")

                try:
                    os.remove(tmp_file)

                except OSError:
                    pass

                continue

            # ❌ Wrong file extension (not audio)
            if not tmp_file.lower().endswith(f".{self.audio_format.lower()}"):
                self._log(f"{self.i18n.t('downloader.log_ignore_extension')} {tmp_file}", "NORMALIZE")

                os.makedirs(os.path.dirname(final_file), exist_ok=True)
                shutil.move(tmp_file, final_file)

                continue

            # ❌ already normalized
            if is_normalized(final_file):
                self._log(f"{self.i18n.t('downloader.log_ignore_already_normalized')}: {final_file}", "NORMALIZE")

                continue

            self._log(f"({index}/{len(files_to_process)}) {self.i18n.t('downloader.log_normalize_init')} {os.path.basename(tmp_file)}", "NORMALIZE")

            try:
                # 🎧 Normalize
                Audio(tmp_file).normalize(target_lufs=-14.0)

                # 📁 guarantees final paste
                os.makedirs(os.path.dirname(final_file), exist_ok=True)

                # 🚚 move to the correct final destination
                shutil.move(tmp_file, final_file)

                self.generated_files.add(os.path.abspath(final_file))
                self.collected_files.append(os.path.abspath(final_file))

                mark_as_normalized(final_file, -14.0)

                self._log(f"OK → {final_file}", "NORMALIZE")

                if self.file_finished_hook:
                    self.file_finished_hook(final_file)

            except Exception as e:
                self._error(f"[NORMALIZE][ERROR] {tmp_file}: {e}")
                self._log(f"{tmp_file}: {e}", "NORMALIZE|ERROR")

        # ===============================
        # 🔹 Move original videos
        # ===============================
        if self.keep_original_file:
            self._move_videos_from_tmp()

        self._log(self.i18n.t("downloader.log_normalize_finish"), "NORMALIZE")

    # ===============================
    # Move original videos from TMP
    # ===============================
    def _move_videos_from_tmp(self) -> None:
        """
        Move original video files from TMP folder to final output folder.
        Only used if `keep_original_file` is True.
        """

        search_dirs: list = [self.tmp_dir, self.tmp_playlist_dir]

        for base_dir in filter(None, search_dirs):
            if not os.path.exists(base_dir):
                continue

            for root, _, files in os.walk(base_dir):
                for file in files:
                    if not file.lower().endswith(".mp4"):
                        continue

                    tmp_video: str = os.path.join(root, file)
                    final_video: str = os.path.join(
                        self.playlist_dir if self.playlist_dir else self.output_path,
                        file
                    )

                    # avoid overwriting
                    if os.path.exists(final_video):
                        continue

                    os.makedirs(os.path.dirname(final_video), exist_ok=True)

                    try:
                        shutil.move(tmp_video, final_video)
                        self.generated_files.add(os.path.abspath(final_video))

                        self._log(f"{self.i18n.t('downloader.log_move_tmp_kept')} {final_video}", "VIDEO")

                    except Exception as e:
                        self._error(f"[VIDEO][ERROR] {tmp_video}: {e}")
                        self._log(f"{tmp_video}: {e}", "VIDEO|ERROR")

    # ===============================
    # Cleanup Methods
    # ===============================
    def _cleanup_files(self) -> None:
        """Remove temporary and intermediate files generated during download."""

        allowed_exts: set = {f".{self.audio_format.lower()}"}

        if self.keep_original_file:
            allowed_exts.add(".mp4")

        # =========================
        # 0️⃣ GLOBAL CLEANING OF .part
        # =========================
        search_dirs: set = set(filter(None, [
            self.output_path,
            self.tmp_dir,
            self.tmp_playlist_dir,
        ]))

        for base_dir in search_dirs:
            if not os.path.isdir(base_dir):
                continue

            for root, _, files in os.walk(base_dir):
                for file in files:
                    if file.endswith(".part"):
                        part_path: str = os.path.join(root, file)

                        try:
                            os.remove(part_path)

                            self._log(f".part {self.i18n.t('downloader.log_cleanup')} {part_path}", "CLEANUP")

                        except Exception as e:
                            self._log(f"{self.i18n.t('downloader.log_error_cleanup')} {part_path} — {e}", "ERROR")

        # =========================
        # 1️⃣ Remove canceled files
        # =========================
        self._delete_canceled_files()

        # =========================
        # 2️⃣ State-based cleaning
        # =========================
        for file_path in list(self.generated_files):
            if not file_path or not os.path.exists(file_path):
                self.generated_files.discard(file_path)

                continue

            if file_path in self.blocked_files:
                continue

            filename: str = os.path.basename(file_path)
            ext: str = os.path.splitext(filename)[1].lower()

            # 🔥 intermediate yt-dlp
            if YTDLP_INTERMEDIATE_RE.search(filename):
                try:
                    os.remove(file_path)

                    self._log(f"{self.i18n.t('downloader.log_cleanup_intermediate')} {file_path}", "CLEANUP")

                except OSError as e:
                    self._log(f"{self.i18n.t('downloader.log_error_cleanup_intermediate')} {file_path} — {e}", "ERROR")

                self.generated_files.discard(file_path)
                continue

            # 🔥 Extensions not allowed
            if ext not in allowed_exts:
                try:
                    os.remove(file_path)
                    self._log(f"{self.i18n.t('downloader.log_cleanup_ext_not_allowed')} {file_path}", "CLEANUP")

                except OSError as e:
                    self._log(f"{self.i18n.t('downloader.log_error_cleanup_remove')} {file_path} — {e}", "ERROR")

                self.generated_files.discard(file_path)

    def _delete_canceled_files(self) -> None:
        """Delete files that were marked as canceled by the user."""

        for file_path in list(self.canceled_files):
            time.sleep(2)

            for attempt in range(5):
                if not os.path.exists(file_path):
                    break

                try:
                    os.remove(file_path)

                    self._log(f"{self.i18n.t('downloader.log_delete_canceled')} {file_path}","CANCEL")
                    break

                except PermissionError:
                    time.sleep(0.5)

            else:
                self._log(f"{self.i18n.t('downloader.log_error_delete_canceled')} {file_path}", "CANCEL")

            self.canceled_files.remove(file_path)

    def pause(self) -> None:
        """Pause the download."""

        if not self._download_active:
            return

        self.paused: bool = True

        if self._download_active:
            self.save_state(paused=self.paused)

        self._set_status(self.i18n.t("downloader.status_pause"))
        self._log(self.i18n.t("downloader.log_pause"), "PAUSE")

        self.pause_event.clear()

    def resume(self) -> None:
        """Resume a paused download."""

        self.paused: bool = False
        self._clear_state()

        self._set_status(self.i18n.t("downloader.status_resume"))
        self._log(self.i18n.t("downloader.log_resume"), "RESUME")

        self.pause_event.set()

    # ===============================
    # State management
    # ===============================
    def save_state(self, paused: bool = False) -> None:
        """
        Save current downloader state to JSON file.
        Always saves a valid and consistent state.

        :param paused: If pause True else False
        :type paused: bool
        """

        # 🔒 Never save invalid state
        if not self.source_url and not self.selected_entries:
            self._log(self.i18n.t("downloader.log_save_state_invalid"), "STATE")

            return

        # ===============================
        # Determine mode
        # ===============================

        if self.allow_playlist:
            mode: str = "playlist"

        else:
            mode: str = "single"

        playlist_selection: Optional[list[dict]] = None

        if mode == "playlist":
            playlist_selection = [
                {
                    "id": e.get("id"),
                    "title": e.get("title"),
                    "playlist_title": e.get("playlist_title")
                }
                for e in self.selected_entries
                if e.get("id")
            ]

        # ===============================
        # Final state (ALWAYS VALID)
        # ===============================
        state: dict = {
            "mode": mode,
            "url": self.source_url,
            "output_path": self.output_path,
            "audio_format": self.audio_format,
            "quality": self.quality,
            "resolution": self.resolution,
            "allow_playlist": self.allow_playlist,
            "keep_original": self.keep_original_file,
            "normalize_enabled": self.normalize_enabled,
            "paused": paused,
            "playlist_selection": playlist_selection
        }

        with open(self.STATE_FILE, "w", encoding="utf-8") as f:
            json.dump(state, f, indent=2, ensure_ascii=False)

        self._log(f"{self.i18n.t('downloader.log_save_state')} ({self.i18n.t('paused')}={paused}, {self.i18n.t('mode')}={mode}): {self.STATE_FILE}", "STATE")

    def _clear_state(self) -> None:
        """Clear saved downloader state."""

        if os.path.exists(self.STATE_FILE):
            os.remove(self.STATE_FILE)

            self._log(f"{self.i18n.t('downloader.log_clear_state')} {self.STATE_FILE}", "STATE")

    def save_state_on_close(self) -> None:
        """Save current download state if active or paused (for UI close handling)."""

        if self._download_active or self.paused:
            self.save_state(paused=True)

    # ===============================
    # Normalization helper
    # ===============================
    def _collect_files_for_normalize(self) -> List[Tuple[str, str]]:
        """
        Collect audio files from TMP folder and map to final destination paths.

        :return: List of tuples (tmp_file_path, final_file_path)
        :rtype: List[Tuple[str, str]]
        """

        files: List[Tuple[str, str]] = []

        if not self.tmp_dir or not os.path.exists(self.tmp_dir):
            return files

        for root, _, filenames in os.walk(self.tmp_dir):
            for name in filenames:
                if not name.lower().endswith(f".{self.audio_format.lower()}"):
                    continue

                tmp_file: str = os.path.join(root, name)

                # calculate final path REAL
                rel: str = os.path.relpath(tmp_file, self.tmp_dir)
                final_file: str = os.path.join(self.output_path, rel)

                files.append((tmp_file, final_file))

        return files

    @staticmethod
    def get_playlist_folder_name(info: dict) -> str:
        """Get the playlist folder name."""

        title: str = info.get("title", "Playlist")

        return sanitize_filename(title)

    # ===============================
    # Download decision
    # ===============================
    def _should_download(self, base_path: str) -> bool:
        """
        Decide whether a file should be downloaded again.

        :param base_path: Final file path without extension.
        :type base_path: str
        :return: True if download is needed, False otherwise.
        :rtype: bool
        """

        audio_path: str = base_path + f".{self.audio_format.lower()}"
        video_path: str = base_path + ".mp4"

        audio_exists: bool = os.path.exists(audio_path)
        video_exists: bool = os.path.exists(video_path)

        # TODO REMOVE AT THE END
        print("\n================ SHOULD DOWNLOAD ================")
        print(f"BASE PATH           : {base_path}")
        print(f"AUDIO PATH          : {audio_path}")
        print(f"VIDEO PATH          : {video_path}")
        print(f"AUDIO EXISTS        : {audio_exists}")
        print(f"VIDEO EXISTS        : {video_exists}")
        print(f"NORMALIZE ENABLED   : {self.normalize_enabled}")
        print(f"KEEP ORIGINAL VIDEO : {self.keep_original_file}")
        print("\n==================================================")

        # =====================================================
        # Normalize enabled
        # =====================================================
        if self.normalize_enabled:
            if not audio_exists:
                return True

            try:
                normalized: bool = is_normalized(audio_path)

            except Exception as e:
                self._log(f"ERROR: {str(e)}", "ERROR")

                # Force download if LUFS check fails
                return True

            if not normalized:
                return True

            if self.keep_original_file and not video_exists:
                return True

            return False

        # =====================================================
        # 🔹 Without NORMALIZE
        # =====================================================
        if not self.keep_original_file:
            return not audio_exists

        return not (audio_exists and video_exists)

    def _cleanup_empty_dirs(self, root: str) -> None:
        """
        Remove empty directories recursively.

        :param root: The path to the root of the directory tree.
        :type root: str
        """

        if not root or not os.path.exists(root):
            return

        for current, dirs, files in os.walk(root, topdown=False):
            if not dirs and not files:
                try:
                    os.rmdir(current)
                    self._log(f"{self.i18n.t('downloader.log_cleanup_empty')} {current}", "CLEANUP")

                except OSError:
                    pass

    def _cleanup_tmp_normalize(self) -> None:
        """Remove temp normalization folder."""

        if self.tmp_dir and os.path.exists(self.tmp_dir):
            try:
                shutil.rmtree(self.tmp_dir)

                self._log(f"{self.i18n.t('downloader.log_cleanup_tmp_normalize')} {self.tmp_dir}", "CLEANUP")

            except Exception as e:
                self._log(f"{self.i18n.t('downloader.log_error_cleanup_tmp_normalize')} {e}", "ERROR")

    # ===============================
    # Utility / helper methods
    # ===============================
    def _log(self, message: str, level: str = "INFO") -> None:
        """
        Internal logging helper.

        :param message: The message to be logged.
        :type message: str
        :param level: Log level (e.g., INFO, WARNING, ERROR).
        :type level: str
        """

        from datetime import datetime

        timestamp: str = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
        entry: str = f"[{timestamp}] {level}: {message}\n"

        if self.log_hook:
            self.log_hook(entry)

    def log(self, message: str, level: str = "INFO") -> None:
        self._log(message, level)

    def  _set_status(self, message: str) -> None:
        """
        Internal status update helper.

        :param message: The status message.
        :type message: str
        """

        if self.status_hook:
            self.status_hook(message)

    def _error(self, message: str) -> None:
        """

        :param message:
        :return:
        """

        if self.error_hook:
            self.error_hook(message)

    # ===============================
    # Post-download / cancel cleanup
    # ===============================
    def _cleanup_after_cancel_or_finished(self) -> None:
        """
        Cleanup actions after download is finished or canceled.
        Removes TMP folders, deletes canceled files, clears state.
        """

        # Remove TMP playlist folder if exists
        if self.tmp_playlist_dir and os.path.exists(self.tmp_playlist_dir):
            try:
                shutil.rmtree(self.tmp_playlist_dir)
                self._log(f"{self.i18n.t('downloader.log_cleanup_after_cancel_finished_folder')} {self.tmp_playlist_dir}", "CLEANUP")

            except Exception as e:
                self._log(f"{self.i18n.t('downloader.log_error_cleanup_after_cancel_finished')} {e}", "ERROR")

        # Cleanup temporary files (intermediate, .part, etc.)
        self._cleanup_files()

        # Remove TMP normalization folder
        self._cleanup_tmp_normalize()

        # Clear state file
        self._clear_state()

        # Clear empty directories
        self._cleanup_empty_dirs(self.output_path)

        self._download_active = False

        if self.cancel_requested:
            self._set_status(self.i18n.t("downloader.status_canceled"))
            self._log(self.i18n.t("downloader.log_cleanup_after_cancel_finished"), "CANCEL")
        else:
            self._set_status(self.i18n.t("downloader.status_canceled_finish"))
            self._log(self.i18n.t("downloader.log_cleanup_after_cancel_finish"), "DONE")

    def normalize_move_and_clean(self) -> None:
        """
        Handles normalization and cleanup of intermediate files
        according to current state flags.
        """

        if self.normalize_enabled:
            self._normalize_files()

        self._cleanup_files()

        # 🔥 move TMP → final folder
        if self.tmp_playlist_dir and os.path.exists(self.tmp_playlist_dir):
            os.makedirs(self.playlist_dir, exist_ok=True)

            for f in os.listdir(self.tmp_playlist_dir):
                shutil.move(
                    os.path.join(self.tmp_playlist_dir, f),
                    os.path.join(self.playlist_dir, f)
                )

            shutil.rmtree(self.tmp_playlist_dir, ignore_errors=True)

    def skip_current_item(self, reason: str = "") -> None:
        """Skip the current item and continue the download flow."""

        video_id: str = (
            self.current_info.get("id")
            if self.current_info else "unknown"
        )

        msg: str = f"⏭️ Skipping video {video_id}"

        if reason:
            msg += f" — {reason}"

        self._log(msg, "WARNING")

        # Reset auth / retry state
        self.failed_video_id = None

        # Let yt-dlp continue naturally (ignoreerrors=True)
        return

    def _apply_cookies_if_needed(self) -> None:
        if self.cookies_from_browser:
            self.ydl_opts["cookiesfrombrowser"] = (self.cookies_from_browser,)
        else:
            self.ydl_opts.pop("cookiesfrombrowser", None)

    @staticmethod
    def _is_auth_error(msg: str) -> bool:
        msg: str = msg.lower()

        return any(marker in msg for marker in AUTH_ERROR_MARKERS)

    def _try_next_browser_cookie(self) -> bool:
        if self._auth_retry_index >= len(self._auth_retry_browsers):
            return False

        browser = self._auth_retry_browsers[self._auth_retry_index]
        self._auth_retry_index += 1

        self.cookies_from_browser = browser
        self._retrying_auth = True

        self._log(
            f"{self.i18n.t('downloader.log_retrying')} {browser}",
            "AUTH"
        )
        return True

    def get_info(self, *, flat: bool = False) -> dict:
        """
        Extracts and caches yt-dlp info.
        - flat=True  → fast playlist/single metadata
        - flat=False → full info (download-ready)
        """

        if self._cached_info is not None and self._cached_flat == flat:
            return self._cached_info

        self._build_ydl_opts()

        opts = dict(self.ydl_opts)

        if flat:
            opts.update({
                "skip_download": True,
                "extract_flat": True,
                "ignoreerrors": True
            })

        with yt_dlp.YoutubeDL(opts) as ydl:
            info: dict = ydl.extract_info(self.url, download=False)

            if info and info.get("_type") == "url":
                info: dict = ydl.extract_info(info["url"], download=False)

        self._cached_info = info
        self._cached_flat = flat

        return info

    def _apply_browser_cookie(self) -> bool:
        """
        Applies cookiesfrombrowser using the current retry index.
        Returns False if no more browsers available.
        """

        if self._auth_retry_index >= len(self._auth_retry_browsers):
            return False

        browser = self._auth_retry_browsers[self._auth_retry_index]

        self.cookies_from_browser = browser

        self._log(
            f"{self.i18n.t('downloader.log_retrying')}: {browser}",
            "AUTH"
        )

        self._auth_retry_index += 1
        return True

    def _reset_auth_retry(self) -> None:
        self._auth_retry_index = 0
        self._retrying_auth = False
        self.cookies_from_browser = None

    def retry_current_item(self) -> None:
        """
        Retries the current video using browser cookies fallback.
        Called after AUTH_REQUIRED error.
        """

        if self._retrying_auth:
            return

        self._retrying_auth = True

        if not self._apply_browser_cookie():
            self._log(self.i18n.t("downloader.log_retrying_failed"), "AUTH")
            raise RuntimeError("AUTH_FAILED")

        # 🔥 rebuild ydl opts WITH cookies
        self._build_ydl_opts()

        if self.cookies_from_browser:
            self.ydl_opts["cookiesfrombrowser"] = (
                self.cookies_from_browser,
                None,
                None,
                None,
            )

        # 🔁 retry EXACT SAME ITEM
        if self.current_info:
            with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
                ydl.process_ie_result(self.current_info, download=True)

        self._retrying_auth = False

    def _extract_light_info(self, url: str) -> dict:
        """
        Fast, non-auth extraction.
        Cached. Safe for playlists, MIX and selection UI.
        """

        if url in self._extract_cache:
            return self._extract_cache[url]

        ydl_opts = {
            "quiet": True,
            "skip_download": True,
            "extract_flat": True,
            "nocheckcertificate": True,
            "ignoreerrors": True,
        }

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info: TypedDict = ydl.extract_info(url, download=False)

                if info and info.get("_type") == "url":
                    info = ydl.extract_info(info["url"], download=False)

        except Exception as e:
            self._error(str(e))

            info = None

        # 🔥 ABSOLUTE GUARANTEE
        if not isinstance(info, dict):
            info = {}

        self._extract_cache[url] = info

        return info

    @staticmethod
    def _normalize_playlist_entries(info: dict) -> list:
        """
        Normalize playlist entries for selection UI.
        Ensures id, title, duration, restricted flag.
        """

        entries: List[dict] = []

        for e in info.get("entries", []):
            if not e:
                continue

            entries.append({
                "id": e.get("id"),
                "title": e.get("title") or "Unavailable",
                "duration": e.get("duration"),
                "url": e.get("url"),
                "is_restricted": e.get("availability") in (
                    "private",
                    "needs_auth",
                    "subscriber_only"
                ) or e.get("live_status") == "not_live",
            })

        return entries

    def notify_restricted(self, msg: str):
        self._log(msg, "SKIP")

        if self.status_hook:
            self.status_hook(self.i18n.t("downloader.status_notify_restricted"))

        if not self._alerted_private:
            self._alerted_private = True
            self._error(self.i18n.t("downloader.error_notify_restricted"))

    def _cleanup_orphan_tmps(self) -> None:
        """
        Remove leftover TMP folders from previous interrupted sessions.
        Safe to call on startup.
        """

        base = self.output_path

        for name in os.listdir(base):
            if name.startswith(".tmp_playlist_") or name == "temp_normalize":
                path = os.path.join(base, name)

                try:
                    shutil.rmtree(path)
                    self._log(f"{self.i18n.t('downloader.log_cleanup_orphan_tmps')} {path}", "CLEANUP")

                except Exception as e:
                    self._log(f"{self.i18n.t('downloader.log_error_cleanup_orphan_tmps')} {path} — {e}", "ERROR")

    def _build_format_string(self) -> str:
        resolution_map = {
            "Auto": None,
            "480p": 480,
            "720p": 720,
            "1080p": 1080,
        }

        h = resolution_map.get(self.resolution)

        # 🔹 Audio-only
        if not self.keep_original_file and self.audio_format:
            return "bestaudio/best"

        # 🔹 Video + audio com fallback REAL
        if h:
            return (
                f"(bestvideo[height<={h}]/bestvideo)+"
                "bestaudio/best"
            )

        return "bestvideo+bestaudio/best"
