# core/downloader.py

import json
import os
import re
import shutil
import threading
import time
import yt_dlp
import yt_dlp.utils

from tkinter import messagebox
from typing import Optional, Callable, List, Tuple, Any

from core.audio import Audio
from utils.helpers import safe_float
from utils.paths import get_ffmpeg_path
from utils.audio_tags import is_normalized, mark_as_normalized
from utils.sanitize import sanitize_filename


# Regex to detect intermediate files generated by yt-dlp
YTDLP_INTERMEDIATE_RE = re.compile(r"\.f\d+\.(webm|mp4|mkv|m4a|aac|opus)(\.part)?$", re.IGNORECASE)

# Main audio/video extensions
MAIN_EXTS = {".mp3", ".wav", ".flac", ".m4a", ".aac", ".opus", ".mp4", ".mkv", ".webm"}

BROWSER_FALLBACK: list = ["chrome", "edge", "firefox", "opera"]


class Downloader:
    """
    Handles YouTube audio/video downloads using yt-dlp, with support for:
        - Playlist downloads
        - Audio normalization (LUFS)
        - Pause/resume
        - Cancel
        - Keeping original video files
        - Progress and status hooks for UI integration

    Hooks (all optional):
        - progress_hook(percent: float, playlist_index: int, playlist_count: int, status_text: str)
        - status_hook(message: str)
        - file_finished_hook(file_path: str)
        - error_hook(error_message: str)
        - log_hook(log_message: str)
    """

    def __init__(
        self,
        url: str,
        output_path: str,
        audio_format: str = "mp3",
        quality: str = "192",
        allow_playlist: bool = True,
        keep_original_file: bool = False,
        normalize_enabled: bool = False,
        progress_hook: Optional[Callable[..., None]] = None,
        status_hook: Optional[Callable[[str], None]] = None,
        file_finished_hook: Optional[Callable[[str], None]] = None,
        error_hook: Optional[Callable[[str], None]] = None,
        log_hook: Optional[Callable[[str], None]] = None,
        state_file: Optional[str] = None,
    ) -> None:
        # ===============================
        # Core configuration
        # ===============================
        self.pending_pause: bool = None
        self.url = url
        self.output_path = output_path
        self.audio_format = audio_format
        self.quality = quality
        self.allow_playlist = allow_playlist
        self.keep_original_file = keep_original_file
        self.normalize_enabled = normalize_enabled

        # ===============================
        # Hooks for UI/controller callbacks
        # ===============================
        self.progress_hook = progress_hook
        self.status_hook = status_hook
        self.file_finished_hook = file_finished_hook
        self.error_hook = error_hook
        self.log_hook = log_hook

        # ===============================
        # Internal state
        # ===============================
        self.ffmpeg_path = get_ffmpeg_path()
        self.generated_files: set[str] = set()
        self.canceled_files: set[str] = set()
        self.files_to_normalize: List[Tuple[str, str]] = []
        self.collected_files: list[str] = []
        self.tmp_dir: Optional[str] = None
        self.tmp_playlist_dir: Optional[str] = None
        self.playlist_dir: Optional[str] = None
        self.playlist_index: Optional[int] = None
        self.playlist_count: Optional[int] = None

        self.cancel_requested: bool = False
        self.cancel_after_current: bool = False
        self.keep_after_cancel: bool = False

        self.cookies_from_browser: Optional[str] = None
        self.auth_retry_attempted: bool = False
        self.browser_retry_index: int = 0

        self.paused: bool = False
        self.pause_event: threading.Event = threading.Event()
        self.pause_event.set()  # Not paused by default

        self.selected_entries: Optional[List[dict]] = None
        self.blocked_files: set[str] = set()
        self.canceled_titles: set[str] = set()

        self._download_active: bool = False
        self.STATE_FILE: Optional[str] = state_file or os.path.join(self.output_path, ".download_state.json")

        self.ydl_opts: dict[str, Any] = {}

        self.current_info: Optional[dict] = None
        self.failed_video_id: str | None = None

        # ===============================
        # Internal thread safety lock
        # ===============================
        self._lock = threading.Lock()

    # ===============================
    # Public methods
    # ===============================
    def start(self) -> None:
        """Start the download process in the current thread."""

        self._download_active = True
        self.tmp_playlist_dir = None

        try:
            # =============================
            # 1️⃣ Initialization
            # =============================
            self._prepare_dirs()

            # =============================
            # 2️⃣ Extract info WITHOUT downloading
            # =============================
            self._build_ydl_opts() # ✅ Guarantees ydl_opts

            # Apply cookies early if already set
            if self.cookies_from_browser:
                self.ydl_opts["cookiesfrombrowser"] = (self.cookies_from_browser, None)

            with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
                try:
                    info = ydl.extract_info(self.url, download=False)

                except yt_dlp.utils.ExtractorError as e:
                    msg: bool = str(e).lower()

                    # 🔥 Capture the ID of the failed video.
                    video_id = getattr(e, "video_id", None)

                    if video_id:
                        self.failed_video_id: Optional[str] = video_id

                    if "private video" in msg or "sign in" in msg or "age-restricted" in msg:
                        raise RuntimeError(f"AUTH_REQUIRED::{str(e)}")

                    raise

            # ============================
            # 3️⃣ PLAYLIST (WITH TMP)
            # ============================
            if self.allow_playlist and "entries" in info:
                self._download_playlist(info)

            # ============================
            # 4️⃣ SINGLE (NO TMP)
            # ============================
            else:
                self._download_single(info)

            # =============================
            # 5️⃣ FINAL OK
            # =============================
            if self.status_hook:
                self.status_hook("Download complete ✔")

            self._log("Download complete", level="DONE")

        except Exception as e:
            msg: str = str(e)

            if msg.startswith("AUTH_REQUIRED::"):
                raise

            if self.error_hook:
                self.error_hook(msg)

            if self.log_hook:
                self._log(f"Download failed: {msg}", level="ERROR")

        finally:
            if not self.paused:
                self._finalize_download()

    # ===============================
    # Internal methods (download flow)
    # ===============================
    def _prepare_dirs(self) -> None:
        """Create necessary output directories."""

        os.makedirs(self.output_path, exist_ok=True)

        self.generated_files.clear()
        self.canceled_files.clear()
        self.collected_files.clear()
        self.files_to_normalize.clear()

        self._set_status("Starting download...")
        self._log("Preparing directories...", level="START")

    def _build_ydl_opts(self) -> None:
        """
        Build yt-dlp options dict according to current settings:
        playlist, normalization, format, quality, etc.
        """

        base_output = self.output_path

        # ==============================
        # 🔹 NORMALIZING IS AN ABSOLUTE PRIORITY
        # ==============================
        if self.normalize_enabled:
            self.tmp_dir = os.path.join(base_output, "temp_normalize")
            os.makedirs(self.tmp_dir, exist_ok=True)
            output_dir = self.tmp_dir

        # ===============================
        # 🔹 NO NORMALIZE → you can use playlist's tmp
        # ===============================
        elif self.allow_playlist and self.tmp_playlist_dir:
            output_dir = self.tmp_playlist_dir

        # =============================
        # 🔹 NO NORMALIZE AND NO PLAYLIST
        # =============================
        else:
            output_dir = base_output

        self.ydl_opts = {
            "format": "bestvideo+bestaudio/best",
            "ffmpeg_location": self.ffmpeg_path,

            "outtmpl": os.path.join(
                output_dir,
                "%(title)s [%(id)s].%(ext)s"
            ),

            "noplaylist": not self.allow_playlist,
            "merge_output_format": "mp4",
            "external_downloader_args": ["-nostdin"],
            "keepvideo": self.keep_original_file,

            "progress_hooks": [self._progress_hook],
            "postprocessor_hooks": [self._postprocessor_hook],

            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": self.audio_format,
                    "preferredquality": self.quality,
                }
            ],

            "restrictfilenames": True,
            "nopart": False,
            "quiet": True,
            "ignoreerrors": True,
            "continuedl": True,

            "extractor_args": {
                "youtube": {
                    "player_client": ["android"]
                }
            }
        }


        # Apply cookies from browser (runtime only)
        if self.cookies_from_browser:
            self.ydl_opts["cookiesfrombrowser"] = (
                self.cookies_from_browser,
                None,
                None,
                None,
            )

    # ===============================
    # Internal download methods
    # ===============================
    def _download_playlist(self, info: dict) -> None:
        """
        Handle playlist download using temporary directory if normalization is enabled.
        Filters already downloaded items and selected entries.

        :param info: Extracted info dict from yt-dlp for the playlist.
        :type info: dict
        """

        playlist_name: str = sanitize_filename(info.get("title", "Playlist"))
        self.playlist_dir: str = os.path.join(self.output_path, playlist_name)

        # Temporary folder for playlist processing
        self.tmp_playlist_dir: str = os.path.join(
            self.output_path,
            f".tmp_playlist_{playlist_name}_{int(time.time())}"
        )

        os.makedirs(self.tmp_playlist_dir, exist_ok=True)

        # Rebuild yt-dlp options pointing to TMP folder if not normalizing
        self._build_ydl_opts()

        if not self.normalize_enabled:
            self.ydl_opts["outtmpl"]: dict = os.path.join(
                self.tmp_playlist_dir,
                "%(title)s [%(id)s].%(ext)s"
            )

        selected_ids: set = None

        if self.selected_entries:
            selected_ids: set = {e.get("id") for e in self.selected_entries} if self.selected_entries else set()

        filtered_entries: list = []

        for entry in info.get("entries", []):
            if not entry:
                continue

            video_id: str = entry.get("id")

            if not video_id:
                continue

            if selected_ids and video_id not in selected_ids:
                continue

            title: str = sanitize_filename(entry.get("title", "untitled"))
            final_base: str = os.path.join(
                self.playlist_dir,
                f"{title} [{video_id}]"
            )

            if self._should_download(final_base):
                filtered_entries.append(entry)

            else:
                self._log(f"Skipping: {title}", level="CACHE")

        if not filtered_entries:
            self._log("No new item to download", level="CACHE")
            shutil.rmtree(self.tmp_playlist_dir, ignore_errors=True)

            return

        info["entries"]: dict = filtered_entries

        with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
            for entry in info["entries"]:
                if not entry:
                    continue

                # 🔥 cache current item
                self.current_info = entry
                self.failed_video_id = entry.get("id")

                ydl.process_ie_result(entry, download=True)

    def _download_single(self, info: dict) -> None:
        """
         Handle single video download (no playlist).

        :param info: Extracted info dict from yt-dlp.
        :type info: dict
        """

        self._build_ydl_opts()

        video_id: str = info.get("id")
        title: str = sanitize_filename(info.get("title", "untitled"))

        if video_id:
            base_path: str = os.path.join(
                self.output_path,
                f"{title} [{video_id}]"
            )

            if not self._should_download(base_path):
                self._log("File already exists, skipping download", level="CACHE")

                return

        # 🔥 Cache info for retry
        self.current_info = info
        self.failed_video_id = info.get("id")

        with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
            ydl.process_ie_result(info, download=True)

    def _finalize_download(self) -> None:
        """
        Actions to finalize download after yt-dlp completes.
        Handles normalization, moving TMP files, cleaning state.
        """

        # =============================
        # CANCELLED + KEEP
        # =============================
        if self.cancel_requested and self.keep_after_cancel:
            self._log("Canceled with keep", level="CANCEL")

            self.normalize_move_and_clean()

            # 🔥 SINGLE + NORMALIZE → move everything from the temp folder to normalize
            if (
                    self.normalize_enabled
                    and not self.allow_playlist
                    and self.tmp_dir
                    and os.path.exists(self.tmp_dir)
            ):
                for f in os.listdir(self.tmp_dir):
                    src = os.path.join(self.tmp_dir, f)
                    dst = os.path.join(self.output_path, f)

                    if os.path.exists(dst):
                        continue

                    shutil.move(src, dst)

                shutil.rmtree(self.tmp_dir, ignore_errors=True)

            self._cleanup_after_cancel_or_finished()

            return

        # =============================
        # CANCELED WITHOUT KEEP
        # =============================
        if self.cancel_requested and not self.keep_after_cancel:
            self._log("Canceled with keep", level="CANCEL")

            # 🔥 ERASE ONLY PMS
            if self.tmp_playlist_dir:
                shutil.rmtree(self.tmp_playlist_dir, ignore_errors=True)

            self._cleanup_after_cancel_or_finished()

            return

        # =============================
        # NORMAL FLOW
        # =============================
        if not self.paused:
            self.normalize_move_and_clean()

            self._cleanup_after_cancel_or_finished()

    # ===============================
    # Cancel method
    # ===============================
    def cancel(self, after_current: bool = False) -> None:
        """
        Cancel the download.

        :param after_current: If True, cancel after the current playlist item finishes.
        :type after_current: bool
        """

        self.pause_event.set()

        if after_current and self.allow_playlist:
            self.cancel_after_current: bool = True

            self._log("⏭️ Cancel requested after current item")

        else:
            self.cancel_requested = True
            self.cancel_after_current: bool = False

            self._log("Immediate cancel requested", level="CANCEL")

    # ===============================
    # Hooks for yt-dlp
    # ==============================
    def _progress_hook(self, d: dict) -> None:
        """
        yt-dlp progress hook. Reports progress, handles cancel requests, tracks generated files.

        :param d: yt-dlp progress dictionary.
        :type d: dict
        """

        # 🔥 Apply deferred pause at first progress callback
        if self.pending_pause:
            self.pause_event.clear()
            self.pending_pause = False

        self.pause_event.wait()

        # Captures temporary files from yt-dlp
        for key in ("tmpfilename", "filename"):
            path: str = d.get(key)

            if path:
                self.generated_files.add(os.path.abspath(path))

        # ===============================
        # 1️⃣ Main files only
        # ===============================
        filename: str = d.get("filename") or d.get("tmpfilename")

        # Only show main file progress
        ext: str = os.path.splitext(filename or "")[1].lower()
        is_main_file: bool = ext in MAIN_EXTS

        if is_main_file and filename and hasattr(self, "audio_format") and self.audio_format:
            # Generates a nice display for logs (does not modify files)
            display_filename: str = os.path.basename(filename)
            display_filename: str = re.sub(r'\.f\d+\.', '.', display_filename)  # remove intermediary
            display_filename: str = os.path.splitext(display_filename)[0]  # remove original extension
            display_filename: str = f"{display_filename}.{self.audio_format.lower()}"

            status: str = d.get("status")
            playlist_index: str = d.get("playlist_index")
            playlist_count: str = d.get("playlist_count")

            if status == "downloading":
                downloaded_bytes: float = safe_float(d.get("downloaded_bytes"))
                total_bytes: float = safe_float(d.get("total_bytes") or d.get("total_bytes_estimate"), 1)
                percent: float = (downloaded_bytes / total_bytes * 100) if total_bytes else 0.0
                speed: float = safe_float(d.get("speed"))
                eta: int = int(d.get("eta") or 0)

                downloaded_mb: float = downloaded_bytes / (1024 * 1024)
                total_mb: float = total_bytes / (1024 * 1024)

                status_text: str = f"{percent:5.1f}% — {downloaded_mb:.2f}/{total_mb:.2f} MB — " \
                                   f"{speed / 1024:.2f} KB/s — ETA {eta}s"

                if playlist_index and playlist_count:
                    status_text: str = f"Item {playlist_index}/{playlist_count} — {status_text}"

                if downloaded_bytes == 0:
                    self._log(f"Starting: {display_filename}", level="DOWNLOAD")

                self._log(f"{status_text}", level="DOWNLOAD")

                if self.progress_hook:
                    self.progress_hook(percent, playlist_index, playlist_count, status_text)

            elif status == "finished":
                abs_path: str = os.path.abspath(filename)
                self.generated_files.add(abs_path)

                self._log(f"{display_filename}", level="DONE")

                if self.progress_hook:
                    self.progress_hook(
                        100.0,
                        d.get("playlist_index"),
                        d.get("playlist_count"),
                        f"[DONE] {display_filename}"
                    )
        # ===============================
        # 2️⃣ Immediate Cancellation
        # ===============================
        if self.cancel_requested and not self.cancel_after_current:
            tmp_file: str = d.get("tmpfilename")

            if tmp_file and os.path.exists(tmp_file):
                try:
                    os.remove(tmp_file)
                    self._log(f"Temporary file removed: {tmp_file}", level="CANCEL")

                except Exception as e:
                    self._log(f"Failed to remove temp file: {tmp_file} — {e}", level="ERROR")

            raise yt_dlp.utils.DownloadError("Download canceled by user")

    def _postprocessor_hook(self, d: dict) -> None:
        """
        yt-dlp postprocessor hook. Tracks generated files and handles cancel after current item.

        :param d: yt-dlp progress dictionary.
        :type d: dict
        """

        if d.get("status") != "finished":
            return

        info: dict = d.get("info_dict") or {}

        possible_paths: list = []

        # Collect possible generated paths
        for key in ("filepath", "filename", "_filename"):
            val = d.get(key) or info.get(key)

            if isinstance(val, str):
                possible_paths.append(val)

        requested: str = d.get("requested_downloads")

        if isinstance(requested, list):
            for item in requested:
                path: str = item.get("filepath") or item.get("filename")

                if path:
                    possible_paths.append(path)

        for path in possible_paths:
            abs_path: str = os.path.abspath(path)
            self.generated_files.add(abs_path)

        # Handle cancel after current playlist item
        if self.cancel_after_current:
            self.cancel_after_current = False

            keep: bool = True
            main_file: str = possible_paths[-1] if possible_paths else None

            if main_file and os.path.exists(main_file):
                keep: bool = messagebox.askyesno(
                    "Cancel playlist",
                    f"Do you want to keep the downloaded file(s)?\n\n{os.path.basename(main_file)}"
                )
                if not keep:
                    self.canceled_files.add(os.path.abspath(main_file))

            self.keep_after_cancel: bool = keep
            self.cancel_requested: bool = True

            self._log(f"Playlist canceled — keep current file? {keep}", level="CANCEL")

    # ===============================
    # Normalization
    # ===============================
    def _normalize_files(self) -> None:
        """
        Normalize audio files in the TMP folder to target LUFS (-14 dB).
        Moves normalized files to final output folder.
        """

        files_to_process: list = self._collect_files_for_normalize()
        tmp_dir: str = self.tmp_dir

        # 🔥 Canceled + Keep → only move files, no normalization
        if self.cancel_requested and self.keep_after_cancel:
            self._log("Cancelled with maintain → skipping normalization", level="NORMALIZE")

            for tmp_file, final_file in files_to_process:
                if not tmp_file or not final_file:
                    continue

                if not os.path.exists(tmp_file):
                    continue

                # ✅ Right destination (playlist vs single)
                if self.allow_playlist and self.playlist_dir:
                    final_file: str = os.path.join(
                        self.playlist_dir,
                        os.path.basename(final_file)
                    )

                os.makedirs(os.path.dirname(final_file), exist_ok=True)

                try:
                    shutil.move(tmp_file, final_file)

                    if self.file_finished_hook:
                        self.file_finished_hook(final_file)

                except OSError:
                    pass

                # 🔥 Move original videos, if necessary
            if self.keep_original_file:
                self._move_videos_from_tmp()

            return

        if not tmp_dir:
            return

        self._log(f"Files collected: {len(files_to_process)}", level="NORMALIZE")

        if not files_to_process:
            self.log_hook("No files to normalize", level="NORMALIZE")

            return

        # ===============================
        # 🔹 Normalize audio
        # ===============================
        for index, (tmp_file, final_file) in enumerate(files_to_process, start=1):
            if not tmp_file or not final_file:
                continue

            tmp_file: str = os.path.abspath(tmp_file)
            final_file: str = os.path.abspath(final_file)

            # ✅ Right destination (playlist vs single)
            if self.allow_playlist and self.playlist_dir:
                final_file: str = os.path.join(
                    self.playlist_dir,
                    os.path.basename(final_file)
                )

            # ❌ file does not exist
            if not os.path.exists(tmp_file):
                self._log(f"File not found: {tmp_file}", level="NORMALIZE")

                continue

            # ❌ canceled file
            if final_file in self.canceled_files:
                self._log(f"Ignored (canceled): {tmp_file}", level="NORMALIZE")

                continue

            # ❌ locked folder or file
            if any(final_file.startswith(os.path.abspath(b)) for b in self.blocked_files):
                self._log(f"Ignored (blocked): {final_file}", level="NORMALIZE")

                try:
                    os.remove(tmp_file)

                except OSError:
                    pass

                continue

            # ❌ Wrong file extension (not audio)
            if not tmp_file.lower().endswith(f".{self.audio_format.lower()}"):
                self._log(f"Ignored (extension): {tmp_file}", level="NORMALIZE")

                os.makedirs(os.path.dirname(final_file), exist_ok=True)
                shutil.move(tmp_file, final_file)

                continue

            # ❌ already normalized
            if is_normalized(final_file):
                self._log(f"[Ignored (already normalized): {final_file}", level="NORMALIZE")

                continue

            self._log(f"({index}/{len(files_to_process)}) Normalizing: {os.path.basename(tmp_file)}", level="NORMALIZE")

            try:
                # 🎧 Normalize
                Audio(tmp_file).normalize(target_lufs=-14.0)

                # 📁 guarantees final paste
                os.makedirs(os.path.dirname(final_file), exist_ok=True)

                # 🚚 move to the correct final destination
                shutil.move(tmp_file, final_file)

                self.generated_files.add(os.path.abspath(final_file))
                self.collected_files.append(os.path.abspath(final_file))

                mark_as_normalized(final_file, -14.0)

                self._log(f"OK → {final_file}", level="NORMALIZE")

                if self.file_finished_hook:
                    self.file_finished_hook(final_file)

            except Exception as e:
                if self.error_hook:
                    self.error_hook(f"[NORMALIZE][ERROR] {tmp_file}: {e}")
                    self._log(f"{tmp_file}: {e}", level="NORMALIZE|ERROR")

        # ===============================
        # 🔹 Move original videos
        # ===============================
        if self.keep_original_file:
            self._move_videos_from_tmp()

        self._log("Finished", level="NORMALIZE")

    # ===============================
    # Move original videos from TMP
    # ===============================
    def _move_videos_from_tmp(self) -> None:
        """
        Move original video files from TMP folder to final output folder.
        Only used if `keep_original_file` is True.
        """

        search_dirs: list = [self.tmp_dir, self.tmp_playlist_dir]

        for base_dir in filter(None, search_dirs):
            if not os.path.exists(base_dir):
                continue

            for root, _, files in os.walk(base_dir):
                for file in files:
                    if not file.lower().endswith(".mp4"):
                        continue

                    tmp_video: str = os.path.join(root, file)
                    final_video: str = os.path.join(
                        self.playlist_dir if self.playlist_dir else self.output_path,
                        file
                    )

                    # avoid overwriting
                    if os.path.exists(final_video):
                        continue

                    os.makedirs(os.path.dirname(final_video), exist_ok=True)

                    try:
                        shutil.move(tmp_video, final_video)
                        self.generated_files.add(os.path.abspath(final_video))

                        self._log(f"Kept: {final_video}", level="VIDEO")

                    except Exception as e:
                        if self.error_hook:
                            self.error_hook(f"[VIDEO][ERROR] {tmp_video}: {e}")
                            self._log(f"{tmp_video}: {e}", level="VIDEO|ERROR")

    # ===============================
    # Cleanup Methods
    # ===============================
    def _cleanup_files(self) -> None:
        """Remove temporary and intermediate files generated during download."""

        allowed_exts: set = {f".{self.audio_format.lower()}"}

        if self.keep_original_file:
            allowed_exts.add(".mp4")

        # =========================
        # 0️⃣ GLOBAL CLEANING OF .part
        # =========================
        search_dirs: set = set(filter(None, [
            self.output_path,
            self.tmp_dir,
            self.tmp_playlist_dir,
        ]))

        for base_dir in search_dirs:
            if not os.path.isdir(base_dir):
                continue

            for root, _, files in os.walk(base_dir):
                for file in files:
                    if file.endswith(".part"):
                        part_path: str = os.path.join(root, file)

                        try:
                            os.remove(part_path)

                            self._log(f".part removed: {part_path}", level="CLEANUP")

                        except Exception as e:
                            self._log(f"Failed to remove .part: {part_path} — {e}", level="ERROR")

        # =========================
        # 1️⃣ Remove canceled files
        # =========================
        self._delete_canceled_files()

        # =========================
        # 2️⃣ State-based cleaning
        # =========================
        for file_path in list(self.generated_files):
            if not file_path or not os.path.exists(file_path):
                self.generated_files.discard(file_path)

                continue

            if file_path in self.blocked_files:
                continue

            filename: str = os.path.basename(file_path)
            ext: str = os.path.splitext(filename)[1].lower()

            # 🔥 intermediate yt-dlp
            if YTDLP_INTERMEDIATE_RE.search(filename):
                try:
                    os.remove(file_path)

                    self._log(f"Intermediate removed: {file_path}", level="CLEANUP")

                except OSError as e:
                    self._log(f"Failed to remove intermediary: {file_path} — {e}", level="ERROR")

                self.generated_files.discard(file_path)
                continue

            # 🔥 Extensions not allowed
            if ext not in allowed_exts:
                try:
                    os.remove(file_path)
                    self._log(f"File removed (ext not allowed): {file_path}", level="CLEANUP")

                except OSError as e:
                    self._log(f"Failed to remove file: {file_path} — {e}", level="ERROR")

                self.generated_files.discard(file_path)

    def _delete_canceled_files(self) -> None:
        """Delete files that were marked as canceled by the user."""

        for file_path in list(self.canceled_files):
            time.sleep(2)

            for attempt in range(5):
                if not os.path.exists(file_path):
                    break

                try:
                    os.remove(file_path)

                    self._log(f"File deleted: {file_path}",level="CANCEL")
                    break

                except PermissionError:
                    time.sleep(0.5)

            else:
                self._log(f"File could NOT be deleted (in use): {file_path}", level="CANCEL")

            self.canceled_files.remove(file_path)

    def pause(self) -> None:
        """Pause the download."""

        if not self._download_active:
            return

        self.paused: bool = True

        if self._download_active:
            self.save_state(paused=True)

        self._set_status("⏸️ Paused")
        self._log("⏸️ Paused by user", level="PAUSE")

        self.pause_event.clear()

    def resume(self) -> None:
        """Resume a paused download."""

        self.paused: bool = False
        self._clear_state()

        self._set_status("▶️ Resuming download...")
        self._log("▶️ Resumed by user", level="RESUME")

        self.pause_event.set()

    # ===============================
    # State management
    # ===============================
    def save_state(self, paused: bool = False) -> None:
        """
        Save current downloader state to JSON file.

        :param paused: If pause True else False
        :type paused: bool
        """

        playlist_selection: Optional[list[dict]] = None

        if self.allow_playlist and self.selected_entries:
            playlist_selection: Optional[list[dict]] = [
                {
                    "id": e.get("id"),
                    "title": e.get("title"),
                    "playlist_title": e.get("playlist_title")
                }
                for e in self.selected_entries
                if e.get("id")
            ]

        state: dict = {
            "url": self.url,
            "output_path": self.output_path,
            "audio_format": self.audio_format,
            "quality": self.quality,
            "allow_playlist": self.allow_playlist,
            "keep_original": self.keep_original_file,
            "normalize_enabled": self.normalize_enabled,
            "paused": paused,
            "playlist_selection": playlist_selection
        }

        with open(self.STATE_FILE, "w", encoding="utf-8") as f:
            json.dump(state, f, indent=2)

        self._log(f"State saved (paused={paused}): {self.STATE_FILE}", level="STATE")

    def _clear_state(self) -> None:
        """Clear saved downloader state."""

        if os.path.exists(self.STATE_FILE):
            os.remove(self.STATE_FILE)

            self._log(f"State file removed: {self.STATE_FILE}", level="STATE")

    def save_state_on_close(self) -> None:
        """Save current download state if active or paused (for UI close handling)."""

        if self._download_active or self.paused:
            self.save_state(paused=self.paused)

    # ===============================
    # Normalization helper
    # ===============================
    def _collect_files_for_normalize(self) -> List[Tuple[str, str]]:
        """
        Collect audio files from TMP folder and map to final destination paths.

        :return: List of tuples (tmp_file_path, final_file_path)
        :rtype: List[Tuple[str, str]]
        """

        files: List[Tuple[str, str]] = []

        if not self.tmp_dir or not os.path.exists(self.tmp_dir):
            return files

        for root, _, filenames in os.walk(self.tmp_dir):
            for name in filenames:
                if not name.lower().endswith(f".{self.audio_format.lower()}"):
                    continue

                tmp_file: str = os.path.join(root, name)

                # calculate final path REAL
                rel: str = os.path.relpath(tmp_file, self.tmp_dir)
                final_file: str = os.path.join(self.output_path, rel)

                files.append((tmp_file, final_file))

        return files

    def _find_existing_file_by_id(self, info_dict: dict) -> None | str:
        """
        Search the final directory for a file containing the video ID.
        It is independent of playlist, normalize, or sanitize.
        """

        video_id: str = info_dict.get("id")

        if not video_id:
            return None

        ext: str = f".{self.audio_format.lower()}"

        search_root: str = self.output_path

        if self.allow_playlist and self.playlist_dir:
            search_root: str = self.playlist_dir

        for root, _, files in os.walk(search_root):
            for f in files:
                if video_id in f and f.lower().endswith(ext):
                    return os.path.join(root, f)

        return None

    @staticmethod
    def get_playlist_folder_name(info: dict) -> str:
        """Get the playlist folder name."""

        title: str = info.get("title", "Playlist")

        return sanitize_filename(title)

    # ===============================
    # Download decision
    # ===============================
    def _should_download(self, base_path: str) -> bool:
        """
        Decide whether a file should be downloaded again.

        :param base_path: Final file path without extension.
        :type base_path: str
        :return: True if download is needed, False otherwise.
        :rtype: bool
        """

        audio_path: str = base_path + f".{self.audio_format.lower()}"
        video_path: str = base_path + ".mp4"

        audio_exists: bool = os.path.exists(audio_path)
        video_exists: bool = os.path.exists(video_path)

        # TODO REMOVE AT THE END
        print("\n================ SHOULD DOWNLOAD ================")
        print(f"BASE PATH           : {base_path}")
        print(f"AUDIO PATH          : {audio_path}")
        print(f"VIDEO PATH          : {video_path}")
        print(f"AUDIO EXISTS        : {audio_exists}")
        print(f"VIDEO EXISTS        : {video_exists}")
        print(f"NORMALIZE ENABLED   : {self.normalize_enabled}")
        print(f"KEEP ORIGINAL VIDEO : {self.keep_original_file}")
        print("\n==================================================")

        # =====================================================
        # Normalize enabled
        # =====================================================
        if self.normalize_enabled:
            if not audio_exists:
                return True

            try:
                normalized: bool = is_normalized(audio_path)

            except Exception as e:
                self._log(f"ERROR: {str(e)}", level="ERROR")

                # Force download if LUFS check fails
                return True

            if not normalized:
                return True

            if self.keep_original_file and not video_exists:
                return True

            return False

        # =====================================================
        # 🔹 Without NORMALIZE
        # =====================================================
        if not self.keep_original_file:
            return not audio_exists

        return not (audio_exists and video_exists)

    def _cleanup_empty_dirs(self, root: str) -> None:
        """
        Remove empty directories recursively.

        :param root: The path to the root of the directory tree.
        :type root: str
        """

        if not root or not os.path.exists(root):
            return

        for current, dirs, files in os.walk(root, topdown=False):
            if not dirs and not files:
                try:
                    os.rmdir(current)
                    self._log(f"Empty folder removed: {current}", level="CLEANUP")

                except OSError:
                    pass

    def _cleanup_tmp_normalize(self) -> None:
        """Remove temp normalization folder."""

        if self.tmp_dir and os.path.exists(self.tmp_dir):
            try:
                shutil.rmtree(self.tmp_dir)

                self._log(f"temp_normalize removed: {self.tmp_dir}", level="CLEANUP")

            except Exception as e:
                if self.log_hook:
                    self.log_hook(f"[ERROR] Failed to remove temp_normalize: {e}")
                    self._log(f"Failed to remove temp_normalize: {e}", level="ERROR")

    def retry_current_item(self) -> None:
        """
        Retry only the failed item using cached info.
        No re-extract, no playlist reprocessing.
        """

        if not self.current_info:
            self.skip_current_item("no cached info for retry")

            return

        video_id: str = self.current_info.get("id", "unknown")

        # Rebuild yt-dlp options including cookiesfrombrowser
        self._build_ydl_opts()

        # 🔥 retry settings
        self.ydl_opts["ignoreerrors"] = True
        self.ydl_opts["continuedl"] = True
        self.ydl_opts["noplaylist"] = True

        try:
            with yt_dlp.YoutubeDL(self.ydl_opts) as ydl:
                ydl.process_ie_result(self.current_info, download=True)

            self._log(f"Recovered video {video_id}", level="AUTH")

        except Exception as e:
            # 🔥 Fail safe — skip
            self._log(f"Auth retry failed for video {video_id}: {str(e)}", level="WARNING")

            # ⏭️ skip without breaking playlist
            self.skip_current_item(f"auth retry failed")

        # finally:
        # Fique atento aqui
        #     # 🔒 cleanup
        #     self.failed_video_id = None
        #     self.auth_retry_attempted = False

    # ===============================
    # Utility / helper methods
    # ===============================
    def _log(self, message: str, level: str = "INFO") -> None:
        """
        Internal logging helper.

        :param message: The message to be logged.
        :type message: str
        :param level: Log level (e.g., INFO, WARNING, ERROR).
        :type level: str
        """

        from datetime import datetime

        timestamp: str = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
        entry: str = f"[{timestamp}] {level}: {message}\n"

        if self.log_hook:
            self.log_hook(entry)

    def  _set_status(self, message: str) -> None:
        """
        Internal status update helper.

        :param message: The status message.
        :type message: str
        """

        if self.status_hook:
            self.status_hook(message)

    # ===============================
    # Post-download / cancel cleanup
    # ===============================
    def _cleanup_after_cancel_or_finished(self) -> None:
        """
        Cleanup actions after download is finished or canceled.
        Removes TMP folders, deletes canceled files, clears state.
        """

        # Remove TMP playlist folder if exists
        if self.tmp_playlist_dir and os.path.exists(self.tmp_playlist_dir):
            try:
                shutil.rmtree(self.tmp_playlist_dir)
                self._log(f"TMP playlist folder removed: {self.tmp_playlist_dir}", level="CLEANUP")

            except Exception as e:
                self._log(f"Failed to remove TMP playlist folder: {e}", level="ERROR")

        # Cleanup temporary files (intermediate, .part, etc.)
        self._cleanup_files()

        # Remove TMP normalization folder
        self._cleanup_tmp_normalize()

        # Clear state file
        self._clear_state()

        # Delete canceled files if any
        self._delete_canceled_files()

        # Clear empty directories
        self._cleanup_empty_dirs(self.output_path)

        self._download_active = False

        if self.cancel_requested:
            self._set_status("Download canceled ❌")
            self._log("Download canceled", level="CANCEL")
        else:
            self._set_status("Download finished ✔")
            self._log("Download finished", level="DONE")

    def normalize_move_and_clean(self) -> None:
        """
        Handles normalization and cleanup of intermediate files
        according to current state flags.
        """

        if self.normalize_enabled:
            self._normalize_files()

        self._cleanup_files()

        # 🔥 move TMP → final folder
        if self.tmp_playlist_dir and os.path.exists(self.tmp_playlist_dir):
            os.makedirs(self.playlist_dir, exist_ok=True)

            for f in os.listdir(self.tmp_playlist_dir):
                shutil.move(
                    os.path.join(self.tmp_playlist_dir, f),
                    os.path.join(self.playlist_dir, f)
                )

            shutil.rmtree(self.tmp_playlist_dir, ignore_errors=True)

    def set_browser_cookies(self, browser: str) -> None:
        """ Applies browser cookies to yt-dlp options."""

        self.ydl_opts["cookiesfrombrowser"] = (browser, None)

    def get_next_browser(self) -> Optional[str]:
        """Get next browser as fallback"""

        if self.browser_retry_index >= len(BROWSER_FALLBACK):
            return None

        browser: str = BROWSER_FALLBACK[self.browser_retry_index]
        self.browser_retry_index += 1

        return browser

    def skip_current_item(self, reason: str = "") -> None:
        """Skip the current item and continue the download flow."""

        video_id: str = (
            self.current_info.get("id")
            if self.current_info else "unknown"
        )

        msg: str = f"⏭️ Skipping video {video_id}"

        if reason:
            msg += f" — {reason}"

        self._log(msg, level="WARNING")

        # Reset auth / retry state
        self.auth_retry_attempted = False
        self.failed_video_id = None

        # Let yt-dlp continue naturally (ignoreerrors=True)
        return
